/** AUTO-GENERATED by seed/scripts/sync-app-data.mjs */
export { characters as disciples } from "./characters";

export function getDisciples() {
  return import("./characters").then((m) => m.characters.filter((c) => c.id.startsWith("disciple-")));
}
