import type { Relationship } from "@/types";

/** AUTO-GENERATED by seed/scripts/sync-app-data.mjs */
export const relationships: Relationship[] = [
  {
    id: "r-1",
    sourceId: "cassian-reed",
    targetId: "adrian-hale",
    type: "romance",
    label: "Friends → Partners",
    strength: 5,
    minChapter: 1,
    revealedChapter: 1081,
    stages: [{"stage":"strangers","untilChapter":80},{"stage":"friends","untilChapter":500},{"stage":"best-friends","untilChapter":880},{"stage":"loss","untilChapter":1080},{"stage":"love","untilChapter":1200}]
  },
  {
    id: "r-2",
    sourceId: "adrian-hale",
    targetId: "selene-arkwright",
    type: "romance",
    label: "Partners (early)",
    strength: 5,
    minChapter: 3,
    endsChapter: 880
  },
  {
    id: "r-3",
    sourceId: "rowan-hale",
    targetId: "elena-hale",
    type: "family",
    label: "Spouses",
    strength: 4,
    minChapter: 2
  },
  {
    id: "r-4",
    sourceId: "rowan-hale",
    targetId: "adrian-hale",
    type: "family",
    label: "Brothers",
    strength: 4,
    minChapter: 2
  },
  {
    id: "r-5",
    sourceId: "adrian-hale",
    targetId: "rowan-hale",
    type: "family",
    label: "Brothers",
    strength: 4,
    minChapter: 2
  },
  {
    id: "r-6",
    sourceId: "marcus-vale",
    targetId: "iris-vale",
    type: "family",
    label: "Spouses",
    strength: 4,
    minChapter: 5
  },
  {
    id: "r-7",
    sourceId: "marcus-vale",
    targetId: "lily-vale",
    type: "family",
    label: "Parent-Child",
    strength: 4,
    minChapter: 5
  },
  {
    id: "r-8",
    sourceId: "cassian-reed",
    targetId: "selene-arkwright",
    type: "alliance",
    label: "Friendly → Tragic",
    strength: 3,
    minChapter: 97
  },
  {
    id: "r-9",
    sourceId: "cassian-reed",
    targetId: "viktor-drake",
    type: "rivalry",
    label: "Respect → Ideological conflict",
    strength: 4,
    minChapter: 404
  },
  {
    id: "r-10",
    sourceId: "adrian-hale",
    targetId: "viktor-drake",
    type: "rivalry",
    label: "Professional competition",
    strength: 4,
    minChapter: 412
  },
  {
    id: "r-11",
    sourceId: "rowan-hale",
    targetId: "viktor-drake",
    type: "rivalry",
    label: "Mutual respect",
    strength: 4,
    minChapter: 404
  },
  {
    id: "r-12",
    sourceId: "cassian-reed",
    targetId: "velkarion",
    type: "alliance",
    label: "Mutual respect",
    strength: 3,
    minChapter: 721
  },
  {
    id: "r-13",
    sourceId: "nora-winters",
    targetId: "whisper",
    type: "alliance",
    label: "Beast contract",
    strength: 3,
    minChapter: 34
  },
  {
    id: "r-14",
    sourceId: "atlas-hale",
    targetId: "ash",
    type: "alliance",
    label: "Beast contract",
    strength: 3,
    minChapter: 845
  },
  {
    id: "r-15",
    sourceId: "cassian-reed",
    targetId: "aria",
    type: "romance",
    label: "Limbo partnership",
    strength: 5,
    minChapter: 921,
    revealedChapter: 1081
  },
  {
    id: "r-16",
    sourceId: "atlas-hale",
    targetId: "cassian-reed",
    type: "mentor",
    label: "Mentor",
    strength: 3,
    minChapter: 850
  }
];

export function getRelationshipsForCharacter(characterId: string) {
  return relationships.filter(
    (r) => r.sourceId === characterId || r.targetId === characterId
  );
}
