import type { TimelineEvent } from "@/types";

/** AUTO-GENERATED by seed/scripts/sync-app-data.mjs */
export const timelineEvents: TimelineEvent[] = [
  {
    id: "t-1",
    title: "The Last Ordinary Morning",
    description: "Cassian Reed wakes in Ashford on an ordinary Tuesday. By afternoon the sky fractures over the harbor.",
    arcId: "arc-1",
    chapterId: "ch-0001",
    year: 0,
    era: "The Rapture",
    type: "story",
    characterIds: ["cassian-reed"],
    locationIds: ["ashford"],
    importance: "monumental",
  },
  {
    id: "day-zero",
    title: "Day Zero — The Rapture",
    description: "Sky fractures; mana floods Earth; civilization collapses.",
    arcId: "arc-1",
    chapterId: "ch-0001",
    year: 0,
    era: "The Rapture",
    type: "story",
    
    
    importance: "monumental",
  },
  {
    id: "we-are-alone",
    title: "The Last Broadcast",
    description: "Emergency broadcast ends: humanity is alone.",
    arcId: "arc-1",
    chapterId: "ch-0010",
    year: 0,
    era: "Age of Sanctuary",
    type: "story",
    
    
    importance: "minor",
  },
  {
    id: "first-dungeon-sighting",
    title: "First Dungeon Rises",
    description: "Colossal structure emerges; world changes again.",
    arcId: "arc-1",
    chapterId: "ch-0030",
    year: 1,
    era: "Age of Sanctuary",
    type: "story",
    
    
    importance: "minor",
  },
  {
    id: "adrian-cassian-meet",
    title: "The Hunter",
    description: "Adrian and Cassian meet; friendship begins.",
    arcId: "arc-1",
    chapterId: "ch-0081",
    year: 4,
    era: "Age of Sanctuary",
    type: "story",
    characterIds: ["cassian-reed"],
    
    importance: "minor",
  },
  {
    id: "dungeon-entered",
    title: "The First Step Below",
    description: "Expedition enters first dungeon.",
    arcId: "arc-1",
    chapterId: "ch-0120",
    year: 6,
    era: "Age of Sanctuary",
    type: "story",
    
    
    importance: "minor",
  },
  {
    id: "were-not-alone",
    title: "Connected Worlds Map",
    description: "Map of dozens of connected worlds discovered.",
    arcId: "arc-1",
    chapterId: "ch-0180",
    year: 8,
    era: "Age of Sanctuary",
    type: "story",
    
    
    importance: "minor",
  },
  {
    id: "highway-camp-named",
    title: "Highway Camp Named",
    description: "Highway Camp Named",
    arcId: "arc-1",
    chapterId: "ch-0200",
    year: 9,
    era: "Age of Sanctuary",
    type: "story",
    
    
    importance: "minor",
  },
  {
    id: "sanctuary-founded",
    title: "Sanctuary Founded",
    description: "Settlement officially named Sanctuary.",
    arcId: "arc-1",
    chapterId: "ch-0266",
    year: 13,
    era: "Age of Sanctuary",
    type: "milestone",
    
    
    importance: "monumental",
  },
  {
    id: "founder-council",
    title: "Founder Council Created",
    description: "Founder Council Created",
    arcId: "arc-1",
    chapterId: "ch-0300",
    year: 15,
    era: "Age of Sanctuary",
    type: "story",
    
    
    importance: "major",
  },
  {
    id: "viktor-introduced",
    title: "Iron Dominion Introduced",
    description: "Iron Dominion Introduced",
    arcId: "arc-1",
    chapterId: "ch-0404",
    year: 20,
    era: "Age of Sanctuary",
    type: "story",
    characterIds: ["viktor-drake"],
    
    importance: "minor",
  },
  {
    id: "seventh-gate-warning",
    title: "Do Not Open the Seventh Gate",
    description: "Do Not Open the Seventh Gate",
    arcId: "arc-1",
    chapterId: "ch-0590",
    year: 28,
    era: "Age of Sanctuary",
    type: "story",
    
    
    importance: "monumental",
  },
  {
    id: "dragon-accords",
    title: "Dragon Accords Signed",
    description: "Dragon Accords Signed",
    arcId: "arc-1",
    chapterId: "ch-0788",
    year: 36,
    era: "Age of Sanctuary",
    type: "story",
    
    
    importance: "major",
  },
  {
    id: "golden-years-peak",
    title: "Festival of Light",
    description: "Festival of Light",
    arcId: "arc-1",
    chapterId: "ch-0810",
    year: 38,
    era: "Age of Sanctuary",
    type: "story",
    
    
    importance: "minor",
  },
  {
    id: "gate-begins",
    title: "It's Begun",
    description: "Silver fracture on earth; Seventh Gate opening.",
    arcId: "arc-1",
    chapterId: "ch-0800",
    year: 38,
    era: "Age of Sanctuary",
    type: "story",
    
    
    importance: "minor",
  },
  {
    id: "cassian-disappears",
    title: "Cassian Disappears",
    description: "Cassian Disappears",
    arcId: "arc-1",
    chapterId: "ch-0880",
    year: 41,
    era: "Age of Sanctuary",
    type: "story",
    characterIds: ["cassian-reed"],
    
    importance: "minor",
  },
  {
    id: "three-years-pass",
    title: "Three Years Absence",
    description: "Three Years Absence",
    arcId: "arc-1",
    chapterId: "ch-0920",
    year: 44,
    era: "Age of Sanctuary",
    type: "story",
    
    
    importance: "minor",
  },
  {
    id: "limbo-aria",
    title: "Cassian Meets Aria",
    description: "Cassian Meets Aria",
    arcId: "arc-1",
    chapterId: "ch-0921",
    year: 44,
    era: "Age of Sanctuary",
    type: "story",
    
    
    importance: "minor",
  },
  {
    id: "cassian-returns",
    title: "Cassian Returns",
    description: "Cassian Returns",
    arcId: "arc-1",
    chapterId: "ch-1041",
    year: 50,
    era: "Age of Sanctuary",
    type: "story",
    characterIds: ["cassian-reed"],
    
    importance: "minor",
  },
  {
    id: "identity-reveal",
    title: "Identity Revealed",
    description: "Identity Revealed",
    arcId: "arc-1",
    chapterId: "ch-1090",
    year: 51,
    era: "Age of Sanctuary",
    type: "story",
    
    
    importance: "minor",
  },
  {
    id: "cycle-truth",
    title: "Cycle Seven Truth",
    description: "Cycle Seven Truth",
    arcId: "arc-1",
    chapterId: "ch-1140",
    year: 53,
    era: "Age of Sanctuary",
    type: "story",
    
    
    importance: "minor",
  },
  {
    id: "adrian-death",
    title: "Adrian Hale Dies",
    description: "Peaceful death after final conversation with Cassian.",
    arcId: "arc-1",
    chapterId: "ch-1170",
    year: 55,
    era: "Age of Sanctuary",
    type: "story",
    characterIds: ["adrian-hale"],
    
    importance: "minor",
  },
  {
    id: "velkarion-sacrifice",
    title: "Velkarion Sacrifice",
    description: "Velkarion Sacrifice",
    arcId: "arc-1",
    chapterId: "ch-1165",
    year: 54,
    era: "Age of Sanctuary",
    type: "story",
    
    
    importance: "minor",
  },
  {
    id: "seventh-choice",
    title: "The Seventh Choice",
    description: "Cycle broken; Eighth Cycle begins.",
    arcId: "arc-1",
    chapterId: "ch-1175",
    year: 55,
    era: "Age of Sanctuary",
    type: "story",
    
    
    importance: "monumental",
  },
  {
    id: "series-finale",
    title: "The Eighth Dawn",
    description: "The Eighth Dawn",
    arcId: "arc-1",
    chapterId: "ch-1200",
    year: 56,
    era: "Age of Sanctuary",
    type: "story",
    
    
    importance: "minor",
  }
];
