/** AUTO-GENERATED by seed/scripts/compile-chapters.mjs — edit books/echoes-of-the-void/content/chapters/*.md instead */
import type { CompiledChapter } from "@/types";

const CHAPTER_ID_RE = /^ch-(\d+)$/;

export function normalizeChapterId(chapterId: string): string {
  const match = CHAPTER_ID_RE.exec(chapterId);
  if (!match) return chapterId;
  return `ch-${match[1].padStart(4, "0")}`;
}

export const chapters: CompiledChapter[] = [
  {
    "id": "ch-0001",
    "number": 1,
    "title": "The Spare Son's Silence",
    "arcId": "arc-1",
    "volumeTitle": "Volume 1 — The Spare Son's Silence",
    "epigraph": "Some doors open only to prove you were never meant to stay.",
    "epigraphAttribution": "— House proverb, minor nobility",
    "summary": "Elarion Voss leaves a cold House Voss for the Royal Arcane Academy — unwanted, average, and carrying memories of another life he cannot name.",
    "opening": {
      "id": "eov-ch-0001-opening",
      "promptId": "eov-ch-0001-opening",
      "placement": "wide",
      "orientation": "landscape",
      "title": "The Spare Son's Silence",
      "caption": "The road to Eldrathor — a spare son's departure",
      "color": "#8b6b2e"
    },
    "blocks": [
      {
        "type": "paragraph",
        "html": "The carriage smelled of old leather and the damp wool of a cloak no one had bothered to replace. Elarion Voss sat with his hands folded in his lap and watched the province slide past the window — frost on the hedgerows, iron-gray sky, the same muted world he had watched for seventeen years without ever quite belonging to it.",
        "dropCap": true
      },
      {
        "type": "paragraph",
        "html": "His father had not come to the door.",
        "dropCap": false
      },
      {
        "type": "paragraph",
        "html": "\"You are the spare,\" Lord Voss had said the night before, standing in the hall with a ledger open in his hands as if his second son were another line item to be struck through. \"Your brother secures our future. You will secure our access. Do not embarrass House Voss at the Academy.\"",
        "dropCap": false
      },
      {
        "type": "paragraph",
        "html": "No embrace. No blessing. His mother had looked at the floor when he passed her on the stairs, lips pressed thin, as though watching him leave might imply she had loved him once and failed. His older brother had not looked at him at all.",
        "dropCap": false
      },
      {
        "type": "paragraph",
        "html": "Elarion adjusted the strap of a plain satchel — no house servant, no crested escort, no griffon courier. House Voss had spent its grandeur on the heir and its spare on a hired carriage and silence.",
        "dropCap": false
      },
      {
        "type": "paragraph",
        "html": "<em>At least they are consistent,</em> he thought, and was ashamed of the bitterness immediately after.",
        "dropCap": false
      },
      {
        "type": "paragraph",
        "html": "There was another life behind his eyes sometimes — fragments like glass in deep water. Fluorescent lights. A phone that never rang back. A small apartment and a body discovered too late. He had been nobody there, too. A gay boy in a family that tolerated him the way one tolerated weather: acknowledged, endured, never invited indoors.",
        "dropCap": false
      },
      {
        "type": "paragraph",
        "html": "He did not know what to call those memories. Dream, madness, punishment. He pushed them down the way he pushed down everything that made him harder to send away.",
        "dropCap": false
      },
      {
        "type": "paragraph",
        "html": "The road climbed. The air changed — thinner, charged, tasting of ozone and pine resin. Mana, the drivers called it in the villages. The Empire's heart beat louder the nearer you came to Eldrathor.",
        "dropCap": false
      },
      {
        "type": "paragraph",
        "html": "When the Spires finally rose against the horizon, Elarion forgot to breathe.",
        "dropCap": false
      },
      {
        "type": "paragraph",
        "html": "They pierced the bruised winter sky like the black fingers of a drowned giant — obsidian-veined marble, living crystal bridges catching the last light and breaking it into colors that had no names. Carriages and mounted escorts converged on a courtyard vast enough to swallow his entire house whole. Robes of noble colors moved in careful streams. Somewhere a bell tolled, and the sound rang in his teeth.",
        "dropCap": false
      },
      {
        "type": "paragraph",
        "html": "He stepped down alone. His boots found frost-kissed gravel. No one called his name.",
        "dropCap": false
      },
      {
        "type": "paragraph",
        "html": "For a moment he considered turning back — not out of fear of the Academy, but out of the old habit of disappearing before anyone could confirm he was not worth keeping. Then the gates ahead groaned open, runes crawling along the iron like luminous veins, and the hum of ambient magic rolled over him — heavy, electric, indifferent.",
        "dropCap": false
      },
      {
        "type": "paragraph",
        "html": "Elarion Voss walked forward because there was nowhere else left to go.",
        "dropCap": false
      },
      {
        "type": "break"
      },
      {
        "type": "paragraph",
        "html": "The Grand Atrium swallowed sound and returned it changed — softer, reverent, laced with ambition. Witchlight orbs drifted beneath a ceiling lost in stained glass and shadow. Hundreds of young nobles clustered in house colors: mage-track students with wands at their belts, warrior-track youths in leathers that smelled of oil and tempered steel.",
        "dropCap": false
      },
      {
        "type": "paragraph",
        "html": "Elarion kept his head down. Invisibility had always been his safest garment.",
        "dropCap": false
      },
      {
        "type": "paragraph",
        "html": "It failed him in the way failures sometimes did — not with drama, but with a single unwanted clarity.",
        "dropCap": false
      },
      {
        "type": "paragraph",
        "html": "\"You are blocking the east walk,\" said a voice beside him, warm and patient. \"First time?\"",
        "dropCap": false
      },
      {
        "type": "paragraph",
        "html": "He looked up. A golden-haired omega offered a small, genuine smile — the kind that reached the eyes without calculating what they might cost. Sun-warmed herbs and honey in the scent of him; healer's house, almost certainly.",
        "dropCap": false
      },
      {
        "type": "paragraph",
        "html": "\"Yes,\" Elarion said. \"Elarion Voss. House Voss.\"",
        "dropCap": false
      },
      {
        "type": "paragraph",
        "html": "\"Seraphiel Kane.\" A brief bow. \"If you are lost, the orientation dais is that way. If you are terrified, that is also that way. The Academy does not distinguish.\"",
        "dropCap": false
      },
      {
        "type": "paragraph",
        "html": "Elarion laughed despite himself — a short, surprised sound. \"Both, then.\"",
        "dropCap": false
      },
      {
        "type": "paragraph",
        "html": "\"Most of us.\" Seraphiel's gaze flicked over Elarion's plain cloak, his unmarked satchel, the absence of retainers. Something gentle passed across his face, quickly hidden. \"Come. Standing alone in the atrium is how upperclassmen mark prey.\"",
        "dropCap": false
      },
      {
        "type": "paragraph",
        "html": "They walked together only a dozen yards before Seraphiel was pulled aside by a healer instructor with a scroll of names. He raised a hand in apology and vanished into the crowd.",
        "dropCap": false
      },
      {
        "type": "paragraph",
        "html": "Elarion was alone again — but the loneliness felt different now. Lighter, as if someone had proved it could be shared.",
        "dropCap": false
      },
      {
        "type": "paragraph",
        "html": "He found a place near the back of the assembly and listened while Archmage Valeria addressed the new cohort from a raised dais. Her voice was measured iron.",
        "dropCap": false
      },
      {
        "type": "paragraph",
        "html": "\"You are not gifts,\" she said. \"You are investments. Your houses sent you to learn, to ally, to survive. Mages will master craft. Warriors will master Skill. Weakness is not tolerated. Neither is stupidity dressed as pride.\"",
        "dropCap": false
      },
      {
        "type": "paragraph",
        "html": "No mention yet of consorts or crowns. Everyone knew those words waited at eighteen like wolves at a treeline.",
        "dropCap": false
      },
      {
        "type": "paragraph",
        "html": "When the welcoming assessment began, Elarion performed adequately — a basic light charm, a minor levitation, nothing that would make an instructor lean forward. Adequate was his art form.",
        "dropCap": false
      },
      {
        "type": "paragraph",
        "html": "On the last pulse of light from his borrowed rowan wand, the glow fractured wrong for half a heartbeat. An afterimage lingered where he had stood. The upperclassman opposite blinked, swung at empty air, and cursed.",
        "dropCap": false
      },
      {
        "type": "paragraph",
        "html": "A murmur rippled. Elarion's stomach tightened.",
        "dropCap": false
      },
      {
        "type": "paragraph",
        "html": "\"Again,\" called an instructor.",
        "dropCap": false
      },
      {
        "type": "paragraph",
        "html": "He did it again. Normal. Perfectly, boringly normal.",
        "dropCap": false
      },
      {
        "type": "paragraph",
        "html": "He told himself it was fatigue. He told himself it was nothing.",
        "dropCap": false
      },
      {
        "type": "paragraph",
        "html": "Far across the atrium, five figures entered with the inevitability of weather fronts — imperial black and gold, alpha presence rolling ahead of them like heat from a forge. The princes. He saw them only as a crowd sees lightning at the horizon: beautiful, distant, not yet his problem.",
        "dropCap": false
      },
      {
        "type": "paragraph",
        "html": "That night, in a narrow dormitory room overlooking frost-white training grounds, Elarion unpacked alone. The rune-warded bed hummed faintly under his palm — suppression for instincts not yet trained. His reflection in the window was exactly as forgettable as he remembered.",
        "dropCap": false
      },
      {
        "type": "paragraph",
        "html": "He thought of Seraphiel's kindness. He thought of his father's ledger voice. He thought, with a pain so old it felt like furniture, of wanting a life that did not require anyone's permission to matter.",
        "dropCap": false
      },
      {
        "type": "paragraph",
        "html": "Outside, the Spires burned with witchlight against the void.",
        "dropCap": false
      },
      {
        "type": "paragraph",
        "html": "He did not know yet that he would live this morning again — and again — until the world itself begged him to stop.",
        "dropCap": false
      },
      {
        "type": "paragraph",
        "html": "He slept anyway. People who have never been chosen learn early how to rest while they still can.",
        "dropCap": false
      }
    ]
  }
] as CompiledChapter[];

export function resolveChapter(chapterId: string): CompiledChapter | undefined {
  return (
    getChapterById(chapterId) ?? getChapterById(normalizeChapterId(chapterId))
  );
}

export function getChapterById(id: string) {
  return chapters.find((ch) => ch.id === id);
}

export function getChaptersByArc(arcId: string) {
  return chapters.filter((ch) => ch.arcId === arcId);
}

export function getTotalBlocks() {
  return chapters.reduce((sum, ch) => sum + ch.blocks.length, 0);
}

export function getChapterIndex(chapterId: string) {
  const chapter = resolveChapter(chapterId);
  if (!chapter) return -1;
  return chapters.findIndex((ch) => ch.id === chapter.id);
}

/** @deprecated use getTotalBlocks */
export function getTotalPages() {
  return getTotalBlocks();
}

/** @deprecated legacy page index */
export function getGlobalPageIndex(chapterId: string, pageIndex: number) {
  let index = 0;
  for (const chapter of chapters) {
    if (chapter.id === chapterId) return index + pageIndex;
    index += chapter.blocks.length;
  }
  return index;
}

export const chapterSceneRegistry = [
  {
    "id": "eov-ch-0001-opening",
    "chapterId": "ch-0001",
    "chapterTitle": "The Spare Son's Silence",
    "title": "The Spare Son's Silence — Chapter Opening",
    "sceneType": "opening",
    "description": "Elarion Voss leaves a cold House Voss for the Royal Arcane Academy — unwanted, average, and carrying memories of another life he cannot name.",
    "caption": "The road to Eldrathor — a spare son's departure",
    "orientation": "landscape",
    "placement": "wide"
  }
] as const;
