/** AUTO-GENERATED by seed/scripts/sync-book-codex.mjs */
import type { Character } from "@/types";

export const characters: Character[] = [
  {
    "id": "elarion-voss",
    "name": "Elarion Voss",
    "role": "protagonist",
    "description": "Unwanted spare son of minor House Voss. Painfully average in looks and talent. Transmigrator with secret time-loop memories. Inherently kind; eventual embodiment of the End.",
    "traits": [
      "average",
      "kind",
      "secretive",
      "loop-aware"
    ],
    "faction": "House Voss",
    "firstAppearance": "ch-0001",
    "imageColor": "#4a3f6b"
  },
  {
    "id": "lirien-thorne",
    "name": "Lirien Thorne",
    "role": "ally",
    "description": "Charismatic schemer from a house of diplomats and spies. Illusion mage. Ambitious, sharp, not cartoonishly evil.",
    "traits": [
      "charismatic",
      "schemer",
      "illusionist"
    ],
    "faction": "House Thorne",
    "firstAppearance": "ch-0003",
    "imageColor": "#4a3f6b"
  },
  {
    "id": "seraphiel-kane",
    "name": "Seraphiel Kane",
    "role": "ally",
    "description": "Gentle healer-mage. Moral center of the omega cohort. Empathy as strength and liability.",
    "traits": [
      "healer",
      "empathetic",
      "moral"
    ],
    "faction": "House Kane",
    "firstAppearance": "ch-0002",
    "imageColor": "#4a3f6b"
  },
  {
    "id": "vesper-quill",
    "name": "Vesper Quill",
    "role": "ally",
    "description": "Quiet observer and information broker. Shadow-adjacent Skill user with subtle foresight hints.",
    "traits": [
      "quiet",
      "perceptive",
      "secretive"
    ],
    "faction": "House Quill",
    "firstAppearance": "ch-0005",
    "imageColor": "#4a3f6b"
  },
  {
    "id": "aurelius-dawn",
    "name": "Aurelius Dawn",
    "role": "ally",
    "description": "Fierce warrior-track omega. Scarred, proud, battle-hungry. Challenges omega stereotypes.",
    "traits": [
      "warrior",
      "proud",
      "fierce"
    ],
    "faction": "House Dawn",
    "firstAppearance": "ch-0004",
    "imageColor": "#4a3f6b"
  },
  {
    "id": "draven-valerius",
    "name": "Draven Valerius",
    "role": "ally",
    "description": "Crown Prince. Charismatic, possessive, politically sharp. Often Elarion's first-loop romantic focus.",
    "traits": [
      "crown-prince",
      "charismatic",
      "dominant"
    ],
    "faction": "Imperial",
    "firstAppearance": "ch-0006",
    "imageColor": "#8b6b2e"
  },
  {
    "id": "kael-valerius",
    "name": "Kael Valerius",
    "role": "ally",
    "description": "Second prince. Scholar-strategist. Chess-mind; runes, court law, long games.",
    "traits": [
      "strategist",
      "scholar",
      "patient"
    ],
    "faction": "Imperial",
    "firstAppearance": "ch-0006",
    "imageColor": "#8b6b2e"
  },
  {
    "id": "thorne-valerius",
    "name": "Thorne Valerius",
    "role": "ally",
    "description": "Third prince. Brooding shadow. Assassin's grace and secrets within secrets.",
    "traits": [
      "brooding",
      "shadow",
      "lethal"
    ],
    "faction": "Imperial",
    "firstAppearance": "ch-0006",
    "imageColor": "#8b6b2e"
  },
  {
    "id": "riven-valerius",
    "name": "Riven Valerius",
    "role": "ally",
    "description": "Fourth prince. Wild storm. Battle-lust, raw power, impulsive loyalty.",
    "traits": [
      "wild",
      "battle-hungry",
      "loyal"
    ],
    "faction": "Imperial",
    "firstAppearance": "ch-0006",
    "imageColor": "#8b6b2e"
  },
  {
    "id": "soren-valerius",
    "name": "Soren Valerius",
    "role": "ally",
    "description": "Fifth prince. Quiet visionary. Prophecy-adjacent interests. Unsettling calm.",
    "traits": [
      "visionary",
      "calm",
      "unsettling"
    ],
    "faction": "Imperial",
    "firstAppearance": "ch-0006",
    "imageColor": "#8b6b2e"
  },
  {
    "id": "emperor-valerius",
    "name": "Emperor Valerius",
    "role": "antagonist",
    "description": "Sovereign of the Valerian Empire. Arranges alliances, engineers succession games, treats lives as chess pieces.",
    "traits": [
      "tyrant",
      "strategist",
      "cold"
    ],
    "faction": "Imperial",
    "firstAppearance": "ch-0010",
    "imageColor": "#8b6b2e"
  }
] as Character[];
