/** AUTO-GENERATED by seed/scripts/sync-book-codex.mjs */
export type ImageCategory = "characters" | "monsters" | "artifacts" | "equipment" | "dungeons" | "locations" | "companions" | "disciples" | "magic" | "factions" | "timeline" | "scenes";
export type ImageStatus = "present" | "missing";

export interface ImageManifestEntry {
  id: string;
  category: ImageCategory;
  bookSlug: string;
  title: string;
  filename: string;
  relativePath: string;
  publicPath: string;
  status: ImageStatus;
  version?: number;
}

export const imageManifest = {
  generatedAt: "2026-06-30T12:41:53.895Z",
  bookSlug: "echoes-of-the-void",
  summary: { total: 20, present: 15, missing: 5 },
  entries: [
  {
    "id": "elarion-voss",
    "category": "characters",
    "bookSlug": "echoes-of-the-void",
    "title": "Elarion Voss",
    "filename": "elarion-voss.svg",
    "relativePath": "assets/images/echoes-of-the-void/characters/elarion-voss.svg",
    "publicPath": "/assets/images/echoes-of-the-void/characters/elarion-voss.svg",
    "status": "present",
    "version": 1782823234128.615
  },
  {
    "id": "lirien-thorne",
    "category": "characters",
    "bookSlug": "echoes-of-the-void",
    "title": "Lirien Thorne",
    "filename": "lirien-thorne.svg",
    "relativePath": "assets/images/echoes-of-the-void/characters/lirien-thorne.svg",
    "publicPath": "/assets/images/echoes-of-the-void/characters/lirien-thorne.svg",
    "status": "present",
    "version": 1782823234129.719
  },
  {
    "id": "seraphiel-kane",
    "category": "characters",
    "bookSlug": "echoes-of-the-void",
    "title": "Seraphiel Kane",
    "filename": "seraphiel-kane.svg",
    "relativePath": "assets/images/echoes-of-the-void/characters/seraphiel-kane.svg",
    "publicPath": "/assets/images/echoes-of-the-void/characters/seraphiel-kane.svg",
    "status": "present",
    "version": 1782823234129.719
  },
  {
    "id": "vesper-quill",
    "category": "characters",
    "bookSlug": "echoes-of-the-void",
    "title": "Vesper Quill",
    "filename": "vesper-quill.svg",
    "relativePath": "assets/images/echoes-of-the-void/characters/vesper-quill.svg",
    "publicPath": "/assets/images/echoes-of-the-void/characters/vesper-quill.svg",
    "status": "present",
    "version": 1782823234130.7207
  },
  {
    "id": "aurelius-dawn",
    "category": "characters",
    "bookSlug": "echoes-of-the-void",
    "title": "Aurelius Dawn",
    "filename": "aurelius-dawn.svg",
    "relativePath": "assets/images/echoes-of-the-void/characters/aurelius-dawn.svg",
    "publicPath": "/assets/images/echoes-of-the-void/characters/aurelius-dawn.svg",
    "status": "present",
    "version": 1782823234130.7207
  },
  {
    "id": "draven-valerius",
    "category": "characters",
    "bookSlug": "echoes-of-the-void",
    "title": "Draven Valerius",
    "filename": "draven-valerius.svg",
    "relativePath": "assets/images/echoes-of-the-void/characters/draven-valerius.svg",
    "publicPath": "/assets/images/echoes-of-the-void/characters/draven-valerius.svg",
    "status": "present",
    "version": 1782823234131.7207
  },
  {
    "id": "kael-valerius",
    "category": "characters",
    "bookSlug": "echoes-of-the-void",
    "title": "Kael Valerius",
    "filename": "kael-valerius.svg",
    "relativePath": "assets/images/echoes-of-the-void/characters/kael-valerius.svg",
    "publicPath": "/assets/images/echoes-of-the-void/characters/kael-valerius.svg",
    "status": "present",
    "version": 1782823234131.7207
  },
  {
    "id": "thorne-valerius",
    "category": "characters",
    "bookSlug": "echoes-of-the-void",
    "title": "Thorne Valerius",
    "filename": "thorne-valerius.svg",
    "relativePath": "assets/images/echoes-of-the-void/characters/thorne-valerius.svg",
    "publicPath": "/assets/images/echoes-of-the-void/characters/thorne-valerius.svg",
    "status": "present",
    "version": 1782823234132.7217
  },
  {
    "id": "riven-valerius",
    "category": "characters",
    "bookSlug": "echoes-of-the-void",
    "title": "Riven Valerius",
    "filename": "riven-valerius.svg",
    "relativePath": "assets/images/echoes-of-the-void/characters/riven-valerius.svg",
    "publicPath": "/assets/images/echoes-of-the-void/characters/riven-valerius.svg",
    "status": "present",
    "version": 1782823234132.7217
  },
  {
    "id": "soren-valerius",
    "category": "characters",
    "bookSlug": "echoes-of-the-void",
    "title": "Soren Valerius",
    "filename": "soren-valerius.svg",
    "relativePath": "assets/images/echoes-of-the-void/characters/soren-valerius.svg",
    "publicPath": "/assets/images/echoes-of-the-void/characters/soren-valerius.svg",
    "status": "present",
    "version": 1782823234133.7197
  },
  {
    "id": "emperor-valerius",
    "category": "characters",
    "bookSlug": "echoes-of-the-void",
    "title": "Emperor Valerius",
    "filename": "emperor-valerius.svg",
    "relativePath": "assets/images/echoes-of-the-void/characters/emperor-valerius.svg",
    "publicPath": "/assets/images/echoes-of-the-void/characters/emperor-valerius.svg",
    "status": "present",
    "version": 1782823234134.7212
  },
  {
    "id": "eldrathor-spires",
    "category": "locations",
    "bookSlug": "echoes-of-the-void",
    "title": "Eldrathor Spires",
    "filename": "eldrathor-spires.svg",
    "relativePath": "assets/images/echoes-of-the-void/locations/eldrathor-spires.svg",
    "publicPath": "/assets/images/echoes-of-the-void/locations/eldrathor-spires.svg",
    "status": "present",
    "version": 1782823234135.7217
  },
  {
    "id": "royal-arcane-academy",
    "category": "locations",
    "bookSlug": "echoes-of-the-void",
    "title": "Royal Arcane Academy",
    "filename": "royal-arcane-academy.svg",
    "relativePath": "assets/images/echoes-of-the-void/locations/royal-arcane-academy.svg",
    "publicPath": "/assets/images/echoes-of-the-void/locations/royal-arcane-academy.svg",
    "status": "present",
    "version": 1782823234135.7217
  },
  {
    "id": "obsidian-throne",
    "category": "locations",
    "bookSlug": "echoes-of-the-void",
    "title": "Obsidian Throne",
    "filename": "obsidian-throne.svg",
    "relativePath": "assets/images/echoes-of-the-void/locations/obsidian-throne.svg",
    "publicPath": "/assets/images/echoes-of-the-void/locations/obsidian-throne.svg",
    "status": "present",
    "version": 1782823234136.8916
  },
  {
    "id": "academy-arrival",
    "category": "timeline",
    "bookSlug": "echoes-of-the-void",
    "title": "Arrival at Eldrathor",
    "filename": "academy-arrival.png",
    "relativePath": "assets/images/echoes-of-the-void/timeline/academy-arrival.png",
    "publicPath": "/assets/images/echoes-of-the-void/timeline/academy-arrival.png",
    "status": "missing"
  },
  {
    "id": "consort-tournament",
    "category": "timeline",
    "bookSlug": "echoes-of-the-void",
    "title": "Royal Consort Tournament",
    "filename": "consort-tournament.png",
    "relativePath": "assets/images/echoes-of-the-void/timeline/consort-tournament.png",
    "publicPath": "/assets/images/echoes-of-the-void/timeline/consort-tournament.png",
    "status": "missing"
  },
  {
    "id": "first-loop-death",
    "category": "timeline",
    "bookSlug": "echoes-of-the-void",
    "title": "First Death, First Echo",
    "filename": "first-loop-death.png",
    "relativePath": "assets/images/echoes-of-the-void/timeline/first-loop-death.png",
    "publicPath": "/assets/images/echoes-of-the-void/timeline/first-loop-death.png",
    "status": "missing"
  },
  {
    "id": "academy-mage-craft",
    "category": "magic",
    "bookSlug": "echoes-of-the-void",
    "title": "Imperial Magecraft",
    "filename": "academy-mage-craft.png",
    "relativePath": "assets/images/echoes-of-the-void/magic/academy-mage-craft.png",
    "publicPath": "/assets/images/echoes-of-the-void/magic/academy-mage-craft.png",
    "status": "missing"
  },
  {
    "id": "martial-skill-path",
    "category": "magic",
    "bookSlug": "echoes-of-the-void",
    "title": "Skill Martial Arts",
    "filename": "martial-skill-path.png",
    "relativePath": "assets/images/echoes-of-the-void/magic/martial-skill-path.png",
    "publicPath": "/assets/images/echoes-of-the-void/magic/martial-skill-path.png",
    "status": "missing"
  },
  {
    "id": "eov-ch-0001-opening",
    "category": "scenes",
    "bookSlug": "echoes-of-the-void",
    "title": "The Spare Son's Silence — Chapter Opening",
    "filename": "eov-ch-0001-opening.svg",
    "relativePath": "assets/images/echoes-of-the-void/scenes/eov-ch-0001-opening.svg",
    "publicPath": "/assets/images/echoes-of-the-void/scenes/eov-ch-0001-opening.svg",
    "status": "present",
    "version": 1782822679536.2126
  }
] as ImageManifestEntry[],
};

export function getManifestByCategory(category: ImageCategory) {
  return imageManifest.entries.filter((e) => e.category === category);
}
