/** AUTO-GENERATED by seed/scripts/sync-book-codex.mjs */
export const magicSkills = [
  {
    "id": "academy-mage-craft",
    "name": "Imperial Magecraft",
    "type": "magic",
    "description": "Wand spells, potions, runes — external mana manipulation. Mages only; no Skills.",
    "rank": "B",
    "color": "#553c9a",
    "promptId": "academy-mage-craft",
    "firstAppearance": "ch-0001"
  },
  {
    "id": "martial-skill-path",
    "name": "Skill Martial Arts",
    "type": "skill",
    "description": "Internalized mana as streamlined abilities — body reinforcement, weapon arts, acquired Skills.",
    "rank": "B",
    "color": "#553c9a",
    "promptId": "martial-skill-path",
    "firstAppearance": "ch-0001"
  }
];
export const manaLaws: string[] = [];
export const magicMaterials: { id: string; name: string; description: string }[] = [];
export const magicRecipes: { id: string; name: string; description: string }[] = [];
