/** AUTO-GENERATED by seed/scripts/sync-book-codex.mjs */
export const relationships = [
  {
    "id": "elarion-seraphiel",
    "from": "elarion-voss",
    "to": "seraphiel-kane",
    "type": "friendship",
    "description": "First kindness at the Academy — platonic omega bond.",
    "minChapter": 2
  },
  {
    "id": "elarion-draven",
    "from": "elarion-voss",
    "to": "draven-valerius",
    "type": "romantic",
    "description": "Default first-loop romantic path — crown prince and spare omega.",
    "minChapter": 91
  },
  {
    "id": "lirien-aurelius",
    "from": "lirien-thorne",
    "to": "aurelius-dawn",
    "type": "rivalry",
    "description": "Schemer versus warrior — competing strategies in Academy politics.",
    "minChapter": 5
  }
];

export function getRelationshipsForCharacter(id: string) {
  return relationships.filter((r) => r.from === id || r.to === id);
}
