/** AUTO-GENERATED by seed/scripts/sync-book-codex.mjs */
export const timelineEvents = [
  {
    "id": "academy-arrival",
    "title": "Arrival at Eldrathor",
    "era": "Academy Years",
    "description": "Elarion Voss and the cohort of seventeen-year-olds enter the Royal Arcane Academy.",
    "chapter": "ch-0001",
    "minChapter": 1,
    "color": "#4a3f6b",
    "promptId": "academy-arrival"
  },
  {
    "id": "consort-tournament",
    "title": "Royal Consort Tournament",
    "era": "Crown Season",
    "description": "At eighteen, eligible omegas enter the tournament; princes date and choose consorts.",
    "chapter": "ch-0091",
    "minChapter": 91,
    "color": "#4a3f6b",
    "promptId": "consort-tournament"
  },
  {
    "id": "first-loop-death",
    "title": "First Death, First Echo",
    "era": "Loops",
    "description": "Elarion dies and resets to Academy arrival with full memory — known only to him.",
    "chapter": "ch-0226",
    "minChapter": 226,
    "color": "#4a3f6b",
    "promptId": "first-loop-death"
  }
];
