/** AUTO-GENERATED by seed/scripts/sync-book-manifest.mjs */
export interface ManifestChapter {
  id: string;
  number: number;
  title: string;
  volumeId: string;
  volumeNumber: number;
  volumeTitle: string;
  status: string;
  pov?: string;
  synopsis?: string;
}

export interface ManifestVolume {
  id: string;
  number: number;
  title: string;
  chapterStart: number;
  chapterEnd: number;
  ageId: string;
  purpose: string;
}

export const manifestVolumes: ManifestVolume[] = [
  {
    "id": "vol-01",
    "number": 1,
    "title": "The Return",
    "chapterStart": 1,
    "chapterEnd": 9,
    "ageId": "act-1",
    "purpose": "Calder takes the ORCHID detail; Ivo knows him and stays silent; the expedition enters the Orrocanopy and reaches the first stones of Qalen-Sar."
  },
  {
    "id": "vol-02",
    "number": 2,
    "title": "The Name",
    "chapterStart": 10,
    "chapterEnd": 18,
    "ageId": "act-2",
    "purpose": "Ruins, creatures, and Calder's unrecognized memories build to the gallery collapse, where he finally says Ivo's name."
  },
  {
    "id": "vol-03",
    "number": 3,
    "title": "What He Carries",
    "chapterStart": 19,
    "chapterEnd": 27,
    "ageId": "act-3",
    "purpose": "Apology without excuse, Ivo's precise revenge, Calder falls in love, confesses, and is rejected. The warmth is put away."
  },
  {
    "id": "vol-04",
    "number": 4,
    "title": "Three Days",
    "chapterStart": 28,
    "chapterEnd": 36,
    "ageId": "act-4",
    "purpose": "Distance, the Unfinished, the collapse, Calder's injury, Ivo's break, the confession, and the proof Calder heard it."
  },
  {
    "id": "vol-05",
    "number": 5,
    "title": "The Last Question",
    "chapterStart": 37,
    "chapterEnd": 45,
    "ageId": "act-5",
    "purpose": "Partners finish the expedition, refuse the Bell, pay the cost, and live with a hum that has not finished changing."
  }
];

export const manifestChapters: ManifestChapter[] = [
  {
    "id": "ch-0001",
    "number": 1,
    "title": "The Man They Sent",
    "volumeId": "vol-01",
    "volumeNumber": 1,
    "volumeTitle": "The Return",
    "status": "published",
    "pov": "Calder Rhys",
    "synopsis": "At Forward Base Lantern, Major Calder Rhys prepares to guard a scientist he has already decided to dislike, while a dead frequency repeats a warning."
  },
  {
    "id": "ch-0002",
    "number": 2,
    "title": "The Initial",
    "volumeId": "vol-01",
    "volumeNumber": 1,
    "volumeTitle": "The Return",
    "status": "published",
    "pov": "Ivo Maren",
    "synopsis": "Dr. Ivo Maren flies toward a man he has not seen in fourteen years and chooses, with his whole composure, to say nothing."
  },
  {
    "id": "ch-0003",
    "number": 3,
    "title": "Asset Orchid",
    "volumeId": "vol-01",
    "volumeNumber": 1,
    "volumeTitle": "The Return",
    "status": "published",
    "pov": "Calder Rhys",
    "synopsis": "The briefing should be simple. The scientist is not fragile, not impressed, and familiar in a way Calder cannot name."
  },
  {
    "id": "ch-0004",
    "number": 4,
    "title": "People You Mean to Bring Back",
    "volumeId": "vol-01",
    "volumeNumber": 1,
    "volumeTitle": "The Return",
    "status": "published",
    "pov": "Nia Okonkwo",
    "synopsis": "Captain Nia Okonkwo counts the living on the river staging and decides the ghost signal is not a bad radio."
  },
  {
    "id": "ch-0005",
    "number": 5,
    "title": "Scientifically Acceptable",
    "volumeId": "vol-01",
    "volumeNumber": 1,
    "volumeTitle": "The Return",
    "status": "published",
    "pov": "Ivo Maren",
    "synopsis": "Ivo crosses a perimeter because the moths do, and Calder learns that curiosity is not the same thing as stupidity."
  },
  {
    "id": "ch-0006",
    "number": 6,
    "title": "What the Rapids Didn't Do",
    "volumeId": "vol-01",
    "volumeNumber": 1,
    "volumeTitle": "The Return",
    "status": "published",
    "pov": "Sable Venn",
    "synopsis": "Survey Lantern's camp contradicts its obituary. Lieutenant Sable Venn needs a biologist she does not want to trust."
  },
  {
    "id": "ch-0007",
    "number": 7,
    "title": "Look at Its Movement",
    "volumeId": "vol-01",
    "volumeNumber": 1,
    "volumeTitle": "The Return",
    "status": "published",
    "pov": "Calder Rhys",
    "synopsis": "Glass kites hit at dusk. Ivo's eye saves the shot. Calder's hands save Ivo. Respect arrives disguised as anger."
  },
  {
    "id": "ch-0008",
    "number": 8,
    "title": "Not on the Chart",
    "volumeId": "vol-01",
    "volumeNumber": 1,
    "volumeTitle": "The Return",
    "status": "published",
    "pov": "Mateo Solano",
    "synopsis": "The medic treats the wounded, watches a marriage work under orders, and tells Calder the truth about fear that stays quiet."
  },
  {
    "id": "ch-0009",
    "number": 9,
    "title": "The First Stones",
    "volumeId": "vol-01",
    "volumeNumber": 1,
    "volumeTitle": "The Return",
    "status": "published",
    "pov": "Ivo Maren",
    "synopsis": "The causeway of Qalen-Sar rises out of the roots. Ivo almost says a name. The expedition enters the city."
  },
  {
    "id": "ch-0010",
    "number": 10,
    "title": "The Same Knot",
    "volumeId": "vol-02",
    "volumeNumber": 2,
    "volumeTitle": "The Name",
    "status": "published",
    "pov": "Priya Raman",
    "synopsis": "Priya reads a glyph in which ask and finish are the same word, and watches Calder watch Ivo."
  },
  {
    "id": "ch-0011",
    "number": 11,
    "title": "Lullaby",
    "volumeId": "vol-02",
    "volumeNumber": 2,
    "volumeTitle": "The Name",
    "status": "published",
    "pov": "Ivo Maren",
    "synopsis": "Root nuns sing a broken Keeper lullaby. Science and tactics each save a life, and neither man says thank you cleanly."
  },
  {
    "id": "ch-0012",
    "number": 12,
    "title": "Pencil Shavings",
    "volumeId": "vol-02",
    "volumeNumber": 2,
    "volumeTitle": "The Name",
    "status": "published",
    "pov": "Calder Rhys",
    "synopsis": "Rain lifts Calder's blocker for one breath. A classroom tries to surface. He cannot hold it."
  },
  {
    "id": "ch-0013",
    "number": 13,
    "title": "Ask It Something",
    "volumeId": "vol-02",
    "volumeNumber": 2,
    "volumeTitle": "The Name",
    "status": "published",
    "pov": "Ellis Ward",
    "synopsis": "A Mirror Hind wears Sable's posture. Ellis asks it a question, and the mimic fails."
  },
  {
    "id": "ch-0014",
    "number": 14,
    "title": "Six Hours",
    "volumeId": "vol-02",
    "volumeNumber": 2,
    "volumeTitle": "The Name",
    "status": "published",
    "pov": "Rhee Amari",
    "synopsis": "Rhee admits she sat on a Helix transmission. The delay will choose the ground for the fight to come."
  },
  {
    "id": "ch-0015",
    "number": 15,
    "title": "Cardamom",
    "volumeId": "vol-02",
    "volumeNumber": 2,
    "volumeTitle": "The Name",
    "status": "published",
    "pov": "Calder Rhys",
    "synopsis": "Ivo sleeps on his notes. Calder covers him with a jacket and calls it asset management."
  },
  {
    "id": "ch-0016",
    "number": 16,
    "title": "Cache the Metal",
    "volumeId": "vol-02",
    "volumeNumber": 2,
    "volumeTitle": "The Name",
    "status": "published",
    "pov": "Harun Dalca",
    "synopsis": "Harun goes down the Cistern Stair without his gun. The eels are guarding silence. Pavel's voice is still on the stylus."
  },
  {
    "id": "ch-0017",
    "number": 17,
    "title": "The Gallery",
    "volumeId": "vol-02",
    "volumeNumber": 2,
    "volumeTitle": "The Name",
    "status": "published",
    "pov": "Ivo Maren",
    "synopsis": "Ivo crosses a cracked span for a verb. The stone goes. In the collapse he says Calder has always been like this."
  },
  {
    "id": "ch-0018",
    "number": 18,
    "title": "Ivo",
    "volumeId": "vol-02",
    "volumeNumber": 2,
    "volumeTitle": "The Name",
    "status": "published",
    "pov": "Calder Rhys",
    "synopsis": "The classroom returns. Calder speaks the name he never used kindly. Ivo goes still."
  },
  {
    "id": "ch-0019",
    "number": 19,
    "title": "After the Name",
    "volumeId": "vol-03",
    "volumeNumber": 3,
    "volumeTitle": "What He Carries",
    "status": "published",
    "pov": "Calder Rhys",
    "synopsis": "Calder apologizes without romance and without excuse. Ivo refuses to be forgiven where it would look like a scene."
  },
  {
    "id": "ch-0020",
    "number": 20,
    "title": "Technically Correct",
    "volumeId": "vol-03",
    "volumeNumber": 3,
    "volumeTitle": "What He Carries",
    "status": "published",
    "pov": "Ivo Maren",
    "synopsis": "Ivo's revenge is precise, petty, and survivable. Calder likes it, and is ashamed of liking it."
  },
  {
    "id": "ch-0021",
    "number": 21,
    "title": "Leave the Tent",
    "volumeId": "vol-03",
    "volumeNumber": 3,
    "volumeTitle": "What He Carries",
    "status": "published",
    "pov": "Jonah Abebe",
    "synopsis": "Scent-thieves counterfeit a heat. Calder leaves the tent because the protocol is the ethics, and does not bargain his way back."
  },
  {
    "id": "ch-0022",
    "number": 22,
    "title": "The Laugh",
    "volumeId": "vol-03",
    "volumeNumber": 3,
    "volumeTitle": "What He Carries",
    "status": "published",
    "pov": "Calder Rhys",
    "synopsis": "Ivo laughs, unarmed, over a moth. Calder learns the word for what he has been doing and does not say it."
  },
  {
    "id": "ch-0023",
    "number": 23,
    "title": "Too Close",
    "volumeId": "vol-03",
    "volumeNumber": 3,
    "volumeTitle": "What He Carries",
    "status": "published",
    "pov": "Ivo Maren",
    "synopsis": "Ivo notices the tea, the jacket, the jealousy. He is angry at being misunderstood and angrier that he cares."
  },
  {
    "id": "ch-0024",
    "number": 24,
    "title": "Down",
    "volumeId": "vol-03",
    "volumeNumber": 3,
    "volumeTitle": "What He Carries",
    "status": "published",
    "pov": "Jun Park",
    "synopsis": "Helix makes contact. Jun takes a round. Leona Varga has a second shot and does not take it."
  },
  {
    "id": "ch-0025",
    "number": 25,
    "title": "Not While I Wear This",
    "volumeId": "vol-03",
    "volumeNumber": 3,
    "volumeTitle": "What He Carries",
    "status": "published",
    "pov": "Calder Rhys",
    "synopsis": "They are close enough to kiss. Calder stops, names the rank between them, and waits for a yes he has not been given."
  },
  {
    "id": "ch-0026",
    "number": 26,
    "title": "I'm Not Asking You to Say It Back",
    "volumeId": "vol-03",
    "volumeNumber": 3,
    "volumeTitle": "What He Carries",
    "status": "published",
    "pov": "Ivo Maren",
    "synopsis": "Calder confesses with no demand. Ivo refuses because forgiveness is not a schedule and love is not a redemption prize."
  },
  {
    "id": "ch-0027",
    "number": 27,
    "title": "Orders",
    "volumeId": "vol-03",
    "volumeNumber": 3,
    "volumeTitle": "What He Carries",
    "status": "published",
    "pov": "Nia Okonkwo",
    "synopsis": "Calder remains an excellent commander and puts the warmth away. Ivo tells himself the quiet is what he asked for."
  },
  {
    "id": "ch-0028",
    "number": 28,
    "title": "He Doesn't Ask",
    "volumeId": "vol-04",
    "volumeNumber": 4,
    "volumeTitle": "Three Days",
    "status": "published",
    "pov": "Ivo Maren",
    "synopsis": "No one checks whether Ivo has eaten. The safety feels like a room with the furniture removed."
  },
  {
    "id": "ch-0029",
    "number": 29,
    "title": "The Unfinished",
    "volumeId": "vol-04",
    "volumeNumber": 4,
    "volumeTitle": "Three Days",
    "status": "published",
    "pov": "Hester Lang",
    "synopsis": "Partial people know the expedition's names because the Vein repeats patterns. They want the question finished so they can rest."
  },
  {
    "id": "ch-0030",
    "number": 30,
    "title": "The Empty Side",
    "volumeId": "vol-04",
    "volumeNumber": 4,
    "volumeTitle": "Three Days",
    "status": "published",
    "pov": "Ivo Maren",
    "synopsis": "Ivo admits he misses being loved at close range. A flare goes up before he can cross the camp."
  },
  {
    "id": "ch-0031",
    "number": 31,
    "title": "The Break",
    "volumeId": "vol-04",
    "volumeNumber": 4,
    "volumeTitle": "Three Days",
    "status": "published",
    "pov": "Nia Okonkwo",
    "synopsis": "Helix and a Vein-storm collapse the basin. The team splits. Radios die into a dead man's cadence."
  },
  {
    "id": "ch-0032",
    "number": 32,
    "title": "Say It",
    "volumeId": "vol-04",
    "volumeNumber": 4,
    "volumeTitle": "Three Days",
    "status": "published",
    "pov": "Calder Rhys",
    "synopsis": "Ivo is missing. Calder searches until he finds him, and stays between Ivo and the stone long enough to break."
  },
  {
    "id": "ch-0033",
    "number": 33,
    "title": "Don't You Dare",
    "volumeId": "vol-04",
    "volumeNumber": 4,
    "volumeTitle": "Three Days",
    "status": "published",
    "pov": "Ivo Maren",
    "synopsis": "The composure ends. Ivo says Calder's name like a person and will not leave him."
  },
  {
    "id": "ch-0034",
    "number": 34,
    "title": "Day One",
    "volumeId": "vol-04",
    "volumeNumber": 4,
    "volumeTitle": "Three Days",
    "status": "published",
    "pov": "Jonah Abebe",
    "synopsis": "Ivo keeps the vigil and reports the mission to an unconscious man. The team stops pretending this is only duty."
  },
  {
    "id": "ch-0035",
    "number": 35,
    "title": "Day Three",
    "volumeId": "vol-04",
    "volumeNumber": 4,
    "volumeTitle": "Three Days",
    "status": "published",
    "pov": "Ivo Maren",
    "synopsis": "Believing Calder cannot hear, Ivo confesses the years he spent failing to forget him."
  },
  {
    "id": "ch-0036",
    "number": 36,
    "title": "Won",
    "volumeId": "vol-04",
    "volumeNumber": 4,
    "volumeTitle": "Three Days",
    "status": "published",
    "pov": "Calder Rhys",
    "synopsis": "Calder has been awake. He waits until the truth is finished, then smiles and asks if he finally won."
  },
  {
    "id": "ch-0037",
    "number": 37,
    "title": "Still Us",
    "volumeId": "vol-05",
    "volumeNumber": 5,
    "volumeTitle": "The Last Question",
    "status": "published",
    "pov": "Calder Rhys",
    "synopsis": "They are together and still themselves. The Bell is ahead. The sling is not a personality."
  },
  {
    "id": "ch-0038",
    "number": 38,
    "title": "Her Brother",
    "volumeId": "vol-05",
    "volumeNumber": 5,
    "volumeTitle": "The Last Question",
    "status": "published",
    "pov": "Leona Varga",
    "synopsis": "Leona parleys. She will help stop Cho if a record survives that cannot teach anyone how to ask."
  },
  {
    "id": "ch-0039",
    "number": 39,
    "title": "The Listening Court",
    "volumeId": "vol-05",
    "volumeNumber": 5,
    "volumeTitle": "The Last Question",
    "status": "published",
    "pov": "Priya Raman",
    "synopsis": "Priya walks the murals, gives a few of the Unfinished their names back, and decides to break the weapon stanza."
  },
  {
    "id": "ch-0040",
    "number": 40,
    "title": "Lantern",
    "volumeId": "vol-05",
    "volumeNumber": 5,
    "volumeTitle": "The Last Question",
    "status": "published",
    "pov": "Hester Lang",
    "synopsis": "Pavel's warning is still broadcasting because the Marrow finishes patterns, including transmissions. The rapids story dies."
  },
  {
    "id": "ch-0041",
    "number": 41,
    "title": "The Mouth",
    "volumeId": "vol-05",
    "volumeNumber": 5,
    "volumeTitle": "The Last Question",
    "status": "published",
    "pov": "Ivo Maren",
    "synopsis": "Ivo understands the Bell and feels the shape of a cure he does not ask for. Calder does not grab his wrist."
  },
  {
    "id": "ch-0042",
    "number": 42,
    "title": "Cho",
    "volumeId": "vol-05",
    "volumeNumber": 5,
    "volumeTitle": "The Last Question",
    "status": "published",
    "pov": "Calder Rhys",
    "synopsis": "Helix reaches the striker. Aegis fights with one good arm, a beta who knows animals, and eels that hate metal."
  },
  {
    "id": "ch-0043",
    "number": 43,
    "title": "Half",
    "volumeId": "vol-05",
    "volumeNumber": 5,
    "volumeTitle": "The Last Question",
    "status": "published",
    "pov": "Ivo Maren",
    "synopsis": "Cho is half-answered. The resonance is flooded, the wheel broken, Harun pinned, and the cure left in the dark."
  },
  {
    "id": "ch-0044",
    "number": 44,
    "title": "The Record",
    "volumeId": "vol-05",
    "volumeNumber": 5,
    "volumeTitle": "The Last Question",
    "status": "published",
    "pov": "Ivo Maren",
    "synopsis": "They come out of the green. Ivo does not forget. He chooses Calder anyway."
  },
  {
    "id": "ch-0045",
    "number": 45,
    "title": "One Note Higher",
    "volumeId": "vol-05",
    "volumeNumber": 5,
    "volumeTitle": "The Last Question",
    "status": "published",
    "pov": "Calder Rhys",
    "synopsis": "Six months later the team is alive and altered. A listening post hears the Vein change pitch. Not tonight, Ivo says."
  }
];

export function getManifestChapter(id: string) {
  return manifestChapters.find((c) => c.id === id);
}

export function getChaptersByVolume(volumeId: string) {
  return manifestChapters.filter((c) => c.volumeId === volumeId);
}

export function isChapterReadable(id: string, compiledIds: Set<string>) {
  const entry = getManifestChapter(id);
  if (!entry) return false;
  return entry.status === "published" && compiledIds.has(id);
}
