/** AUTO-GENERATED by seed/scripts/sync-book-codex.mjs */
import type { Character } from "@/types";

export const characters: Character[] = [
  {
    "id": "calder-rhys",
    "name": "Calder Rhys",
    "role": "protagonist",
    "description": "Major, Aegis Detachment Seven. Cocky, decorated, and responsible for the people under his voice. He bullied Ivo Maren at St. Briony and does not recognize the man he is assigned to keep alive.",
    "traits": [
      "commander",
      "cocky",
      "loyal",
      "guilty"
    ],
    "faction": "Aegis Seven",
    "firstAppearance": "ch-0001",
    "imageColor": "#8b6b2e"
  },
  {
    "id": "ivo-maren",
    "name": "Ivo Maren",
    "role": "protagonist",
    "description": "Dr. I. Maren, asset ORCHID. A composed field scientist of anomalous biology who recognizes Calder instantly and says nothing. Curiosity overrides his fear until Calder is the one bleeding.",
    "traits": [
      "clinical",
      "guarded",
      "brilliant",
      "dry"
    ],
    "faction": "Anomalous Ecology",
    "firstAppearance": "ch-0002",
    "imageColor": "#4a3f6b"
  },
  {
    "id": "nia-okonkwo",
    "name": "Nia Okonkwo",
    "role": "ally",
    "description": "Captain and second-in-command. Sarcastic, precise, and haunted by a civilian she failed to keep inside a perimeter.",
    "traits": [
      "practical",
      "sarcastic",
      "steady"
    ],
    "faction": "Aegis Seven",
    "firstAppearance": "ch-0001",
    "imageColor": "#718096"
  },
  {
    "id": "mateo-solano",
    "name": "Mateo Solano",
    "role": "ally",
    "description": "Sergeant medic. Blunt and devoted. Bonded to archaeologist Anouk Solano, and professional enough to hate that the bond matters in the field.",
    "traits": [
      "medic",
      "blunt",
      "devoted"
    ],
    "faction": "Aegis Seven",
    "firstAppearance": "ch-0001",
    "imageColor": "#8b6b2e"
  },
  {
    "id": "jun-park",
    "name": "Jun Park",
    "role": "ally",
    "description": "Corporal and sniper. Quiet, exact, bonded to Harun Dalca. Says less than he sees.",
    "traits": [
      "sniper",
      "precise",
      "loyal"
    ],
    "faction": "Aegis Seven",
    "firstAppearance": "ch-0001",
    "imageColor": "#4a3f6b"
  },
  {
    "id": "harun-dalca",
    "name": "Harun Dalca",
    "role": "ally",
    "description": "Sergeant, heavy weapons. Loud loyalty over a fear of enclosed stone. Bonded to Jun Park.",
    "traits": [
      "loud",
      "brave",
      "claustrophobic"
    ],
    "faction": "Aegis Seven",
    "firstAppearance": "ch-0001",
    "imageColor": "#8b6b2e"
  },
  {
    "id": "sable-venn",
    "name": "Sable Venn",
    "role": "ally",
    "description": "Lieutenant, reconnaissance. Competitive and suspicious of analysts. Falls for Ellis Ward because he is right about the living world.",
    "traits": [
      "recon",
      "competitive",
      "guarded"
    ],
    "faction": "Aegis Seven",
    "firstAppearance": "ch-0004",
    "imageColor": "#8b6b2e"
  },
  {
    "id": "rhee-amari",
    "name": "Rhee Amari",
    "role": "ally",
    "description": "Specialist. Engineer and communications. Clever enough to delay a warning, and honest enough to pay for it.",
    "traits": [
      "engineer",
      "radios",
      "contrite"
    ],
    "faction": "Aegis Seven",
    "firstAppearance": "ch-0001",
    "imageColor": "#718096"
  },
  {
    "id": "anouk-solano",
    "name": "Anouk Solano",
    "role": "ally",
    "description": "Archaeologist. Argumentative, evidence-faithful, bonded to Mateo. Fights Hester Lang about whether the city was a temple or a laboratory.",
    "traits": [
      "archaeologist",
      "passionate",
      "sharp"
    ],
    "faction": "Anomalous Ecology",
    "firstAppearance": "ch-0004",
    "imageColor": "#4a3f6b"
  },
  {
    "id": "priya-raman",
    "name": "Priya Raman",
    "role": "ally",
    "description": "Linguist of the Selenqari knot-script. Ivo's friend and the only person on the expedition who knows what Calder was to him before the jungle.",
    "traits": [
      "linguist",
      "loyal",
      "precise"
    ],
    "faction": "Anomalous Ecology",
    "firstAppearance": "ch-0002",
    "imageColor": "#4a3f6b"
  },
  {
    "id": "ellis-ward",
    "name": "Ellis Ward",
    "role": "ally",
    "description": "Field biologist. Talks to specimens. Carries cardamom. Learns he is not dead weight because the animals tell the truth to him first.",
    "traits": [
      "biologist",
      "eccentric",
      "kind"
    ],
    "faction": "Anomalous Ecology",
    "firstAppearance": "ch-0004",
    "imageColor": "#718096"
  },
  {
    "id": "jonah-abebe",
    "name": "Jonah Abebe",
    "role": "ally",
    "description": "Medical researcher for suppressants, venom, and the ethics of both. Keeps the designation protocols from becoming excuses.",
    "traits": [
      "physician",
      "ethical",
      "dry"
    ],
    "faction": "Anomalous Ecology",
    "firstAppearance": "ch-0004",
    "imageColor": "#718096"
  },
  {
    "id": "hester-lang",
    "name": "Hester Lang",
    "role": "ally",
    "description": "Historian and occult specialist. Knew Pavel Ruiz of the lost Survey Lantern. Wants the city preserved and learns preservation is not the same as ringing the Bell.",
    "traits": [
      "historian",
      "stubborn",
      "grieving"
    ],
    "faction": "Anomalous Ecology",
    "firstAppearance": "ch-0004",
    "imageColor": "#8b6b2e"
  },
  {
    "id": "tomas-ibarra",
    "name": "Tomas Ibarra",
    "role": "ally",
    "description": "Virelian liaison captain. Decent, interested in Ivo, and wise enough to take his people back when the Reach starts answering.",
    "traits": [
      "liaison",
      "decent",
      "local"
    ],
    "faction": "Virelia",
    "firstAppearance": "ch-0004",
    "imageColor": "#8b6b2e"
  },
  {
    "id": "adrien-cho",
    "name": "Adrien Cho",
    "role": "antagonist",
    "description": "Director of Helix Meridian. Former Compact cartographer who believes leaving the Marrow unasked is vanity that will cost millions of lives.",
    "traits": [
      "certain",
      "strategic",
      "ruthless"
    ],
    "faction": "Helix Meridian",
    "firstAppearance": "ch-0038",
    "imageColor": "#8b6b2e"
  },
  {
    "id": "leona-varga",
    "name": "Leona Varga",
    "role": "antagonist",
    "description": "Helix field commander. Her brother died in a classified anomaly. She wants a reason more than a weapon, and still steals what she can carry.",
    "traits": [
      "grieving",
      "disciplined",
      "sympathetic"
    ],
    "faction": "Helix Meridian",
    "firstAppearance": "ch-0024",
    "imageColor": "#718096"
  },
  {
    "id": "pavel-ruiz",
    "name": "Pavel Ruiz",
    "role": "ally",
    "description": "Lead of the lost Survey Lantern expedition. He learned not to ask the Marrow what it wants. The jungle is still repeating him.",
    "traits": [
      "dead",
      "warning",
      "scientist"
    ],
    "faction": "Survey Lantern",
    "firstAppearance": "ch-0006",
    "imageColor": "#718096"
  }
] as Character[];
