/** AUTO-GENERATED by seed/scripts/sync-book-codex.mjs */
export type ImageCategory = "characters" | "monsters" | "artifacts" | "equipment" | "dungeons" | "locations" | "companions" | "disciples" | "magic" | "factions" | "timeline" | "scenes";
export type ImageStatus = "present" | "missing";

export interface ImageManifestEntry {
  id: string;
  category: ImageCategory;
  bookSlug: string;
  title: string;
  filename: string;
  relativePath: string;
  publicPath: string;
  status: ImageStatus;
  version?: number;
}

export const imageManifest = {
  generatedAt: "2026-09-26T18:27:59.396Z",
  bookSlug: "the-hollow-canopy",
  summary: { total: 40, present: 0, missing: 40 },
  entries: [
  {
    "id": "calder-rhys",
    "category": "characters",
    "bookSlug": "the-hollow-canopy",
    "title": "Calder Rhys",
    "filename": "calder-rhys.png",
    "relativePath": "assets/images/the-hollow-canopy/characters/calder-rhys.png",
    "publicPath": "/assets/images/the-hollow-canopy/characters/calder-rhys.png",
    "status": "missing"
  },
  {
    "id": "ivo-maren",
    "category": "characters",
    "bookSlug": "the-hollow-canopy",
    "title": "Ivo Maren",
    "filename": "ivo-maren.png",
    "relativePath": "assets/images/the-hollow-canopy/characters/ivo-maren.png",
    "publicPath": "/assets/images/the-hollow-canopy/characters/ivo-maren.png",
    "status": "missing"
  },
  {
    "id": "nia-okonkwo",
    "category": "characters",
    "bookSlug": "the-hollow-canopy",
    "title": "Nia Okonkwo",
    "filename": "nia-okonkwo.png",
    "relativePath": "assets/images/the-hollow-canopy/characters/nia-okonkwo.png",
    "publicPath": "/assets/images/the-hollow-canopy/characters/nia-okonkwo.png",
    "status": "missing"
  },
  {
    "id": "mateo-solano",
    "category": "characters",
    "bookSlug": "the-hollow-canopy",
    "title": "Mateo Solano",
    "filename": "mateo-solano.png",
    "relativePath": "assets/images/the-hollow-canopy/characters/mateo-solano.png",
    "publicPath": "/assets/images/the-hollow-canopy/characters/mateo-solano.png",
    "status": "missing"
  },
  {
    "id": "jun-park",
    "category": "characters",
    "bookSlug": "the-hollow-canopy",
    "title": "Jun Park",
    "filename": "jun-park.png",
    "relativePath": "assets/images/the-hollow-canopy/characters/jun-park.png",
    "publicPath": "/assets/images/the-hollow-canopy/characters/jun-park.png",
    "status": "missing"
  },
  {
    "id": "harun-dalca",
    "category": "characters",
    "bookSlug": "the-hollow-canopy",
    "title": "Harun Dalca",
    "filename": "harun-dalca.png",
    "relativePath": "assets/images/the-hollow-canopy/characters/harun-dalca.png",
    "publicPath": "/assets/images/the-hollow-canopy/characters/harun-dalca.png",
    "status": "missing"
  },
  {
    "id": "sable-venn",
    "category": "characters",
    "bookSlug": "the-hollow-canopy",
    "title": "Sable Venn",
    "filename": "sable-venn.png",
    "relativePath": "assets/images/the-hollow-canopy/characters/sable-venn.png",
    "publicPath": "/assets/images/the-hollow-canopy/characters/sable-venn.png",
    "status": "missing"
  },
  {
    "id": "rhee-amari",
    "category": "characters",
    "bookSlug": "the-hollow-canopy",
    "title": "Rhee Amari",
    "filename": "rhee-amari.png",
    "relativePath": "assets/images/the-hollow-canopy/characters/rhee-amari.png",
    "publicPath": "/assets/images/the-hollow-canopy/characters/rhee-amari.png",
    "status": "missing"
  },
  {
    "id": "anouk-solano",
    "category": "characters",
    "bookSlug": "the-hollow-canopy",
    "title": "Anouk Solano",
    "filename": "anouk-solano.png",
    "relativePath": "assets/images/the-hollow-canopy/characters/anouk-solano.png",
    "publicPath": "/assets/images/the-hollow-canopy/characters/anouk-solano.png",
    "status": "missing"
  },
  {
    "id": "priya-raman",
    "category": "characters",
    "bookSlug": "the-hollow-canopy",
    "title": "Priya Raman",
    "filename": "priya-raman.png",
    "relativePath": "assets/images/the-hollow-canopy/characters/priya-raman.png",
    "publicPath": "/assets/images/the-hollow-canopy/characters/priya-raman.png",
    "status": "missing"
  },
  {
    "id": "ellis-ward",
    "category": "characters",
    "bookSlug": "the-hollow-canopy",
    "title": "Ellis Ward",
    "filename": "ellis-ward.png",
    "relativePath": "assets/images/the-hollow-canopy/characters/ellis-ward.png",
    "publicPath": "/assets/images/the-hollow-canopy/characters/ellis-ward.png",
    "status": "missing"
  },
  {
    "id": "jonah-abebe",
    "category": "characters",
    "bookSlug": "the-hollow-canopy",
    "title": "Jonah Abebe",
    "filename": "jonah-abebe.png",
    "relativePath": "assets/images/the-hollow-canopy/characters/jonah-abebe.png",
    "publicPath": "/assets/images/the-hollow-canopy/characters/jonah-abebe.png",
    "status": "missing"
  },
  {
    "id": "hester-lang",
    "category": "characters",
    "bookSlug": "the-hollow-canopy",
    "title": "Hester Lang",
    "filename": "hester-lang.png",
    "relativePath": "assets/images/the-hollow-canopy/characters/hester-lang.png",
    "publicPath": "/assets/images/the-hollow-canopy/characters/hester-lang.png",
    "status": "missing"
  },
  {
    "id": "tomas-ibarra",
    "category": "characters",
    "bookSlug": "the-hollow-canopy",
    "title": "Tomas Ibarra",
    "filename": "tomas-ibarra.png",
    "relativePath": "assets/images/the-hollow-canopy/characters/tomas-ibarra.png",
    "publicPath": "/assets/images/the-hollow-canopy/characters/tomas-ibarra.png",
    "status": "missing"
  },
  {
    "id": "adrien-cho",
    "category": "characters",
    "bookSlug": "the-hollow-canopy",
    "title": "Adrien Cho",
    "filename": "adrien-cho.png",
    "relativePath": "assets/images/the-hollow-canopy/characters/adrien-cho.png",
    "publicPath": "/assets/images/the-hollow-canopy/characters/adrien-cho.png",
    "status": "missing"
  },
  {
    "id": "leona-varga",
    "category": "characters",
    "bookSlug": "the-hollow-canopy",
    "title": "Leona Varga",
    "filename": "leona-varga.png",
    "relativePath": "assets/images/the-hollow-canopy/characters/leona-varga.png",
    "publicPath": "/assets/images/the-hollow-canopy/characters/leona-varga.png",
    "status": "missing"
  },
  {
    "id": "pavel-ruiz",
    "category": "characters",
    "bookSlug": "the-hollow-canopy",
    "title": "Pavel Ruiz",
    "filename": "pavel-ruiz.png",
    "relativePath": "assets/images/the-hollow-canopy/characters/pavel-ruiz.png",
    "publicPath": "/assets/images/the-hollow-canopy/characters/pavel-ruiz.png",
    "status": "missing"
  },
  {
    "id": "base-lantern",
    "category": "locations",
    "bookSlug": "the-hollow-canopy",
    "title": "Forward Base Lantern",
    "filename": "base-lantern.png",
    "relativePath": "assets/images/the-hollow-canopy/locations/base-lantern.png",
    "publicPath": "/assets/images/the-hollow-canopy/locations/base-lantern.png",
    "status": "missing"
  },
  {
    "id": "orrocanopy",
    "category": "locations",
    "bookSlug": "the-hollow-canopy",
    "title": "The Orrocanopy",
    "filename": "orrocanopy.png",
    "relativePath": "assets/images/the-hollow-canopy/locations/orrocanopy.png",
    "publicPath": "/assets/images/the-hollow-canopy/locations/orrocanopy.png",
    "status": "missing"
  },
  {
    "id": "survey-lantern-camp",
    "category": "locations",
    "bookSlug": "the-hollow-canopy",
    "title": "Survey Lantern Camp",
    "filename": "survey-lantern-camp.png",
    "relativePath": "assets/images/the-hollow-canopy/locations/survey-lantern-camp.png",
    "publicPath": "/assets/images/the-hollow-canopy/locations/survey-lantern-camp.png",
    "status": "missing"
  },
  {
    "id": "qalen-sar",
    "category": "locations",
    "bookSlug": "the-hollow-canopy",
    "title": "Qalen-Sar",
    "filename": "qalen-sar.png",
    "relativePath": "assets/images/the-hollow-canopy/locations/qalen-sar.png",
    "publicPath": "/assets/images/the-hollow-canopy/locations/qalen-sar.png",
    "status": "missing"
  },
  {
    "id": "cistern-stair",
    "category": "locations",
    "bookSlug": "the-hollow-canopy",
    "title": "The Cistern Stair",
    "filename": "cistern-stair.png",
    "relativePath": "assets/images/the-hollow-canopy/locations/cistern-stair.png",
    "publicPath": "/assets/images/the-hollow-canopy/locations/cistern-stair.png",
    "status": "missing"
  },
  {
    "id": "listening-court",
    "category": "locations",
    "bookSlug": "the-hollow-canopy",
    "title": "The Listening Court",
    "filename": "listening-court.png",
    "relativePath": "assets/images/the-hollow-canopy/locations/listening-court.png",
    "publicPath": "/assets/images/the-hollow-canopy/locations/listening-court.png",
    "status": "missing"
  },
  {
    "id": "marrow-bell",
    "category": "locations",
    "bookSlug": "the-hollow-canopy",
    "title": "The Marrow Bell",
    "filename": "marrow-bell.png",
    "relativePath": "assets/images/the-hollow-canopy/locations/marrow-bell.png",
    "publicPath": "/assets/images/the-hollow-canopy/locations/marrow-bell.png",
    "status": "missing"
  },
  {
    "id": "st-briony",
    "category": "locations",
    "bookSlug": "the-hollow-canopy",
    "title": "St. Briony Collegiate",
    "filename": "st-briony.png",
    "relativePath": "assets/images/the-hollow-canopy/locations/st-briony.png",
    "publicPath": "/assets/images/the-hollow-canopy/locations/st-briony.png",
    "status": "missing"
  },
  {
    "id": "st-briony-years",
    "category": "timeline",
    "bookSlug": "the-hollow-canopy",
    "title": "St. Briony",
    "filename": "st-briony-years.png",
    "relativePath": "assets/images/the-hollow-canopy/timeline/st-briony-years.png",
    "publicPath": "/assets/images/the-hollow-canopy/timeline/st-briony-years.png",
    "status": "missing"
  },
  {
    "id": "survey-lantern-lost",
    "category": "timeline",
    "bookSlug": "the-hollow-canopy",
    "title": "Survey Lantern vanishes",
    "filename": "survey-lantern-lost.png",
    "relativePath": "assets/images/the-hollow-canopy/timeline/survey-lantern-lost.png",
    "publicPath": "/assets/images/the-hollow-canopy/timeline/survey-lantern-lost.png",
    "status": "missing"
  },
  {
    "id": "orchid-assignment",
    "category": "timeline",
    "bookSlug": "the-hollow-canopy",
    "title": "The ORCHID detail",
    "filename": "orchid-assignment.png",
    "relativePath": "assets/images/the-hollow-canopy/timeline/orchid-assignment.png",
    "publicPath": "/assets/images/the-hollow-canopy/timeline/orchid-assignment.png",
    "status": "missing"
  },
  {
    "id": "the-name",
    "category": "timeline",
    "bookSlug": "the-hollow-canopy",
    "title": "Calder says Ivo",
    "filename": "the-name.png",
    "relativePath": "assets/images/the-hollow-canopy/timeline/the-name.png",
    "publicPath": "/assets/images/the-hollow-canopy/timeline/the-name.png",
    "status": "missing"
  },
  {
    "id": "the-refusal",
    "category": "timeline",
    "bookSlug": "the-hollow-canopy",
    "title": "The refusal",
    "filename": "the-refusal.png",
    "relativePath": "assets/images/the-hollow-canopy/timeline/the-refusal.png",
    "publicPath": "/assets/images/the-hollow-canopy/timeline/the-refusal.png",
    "status": "missing"
  },
  {
    "id": "three-days",
    "category": "timeline",
    "bookSlug": "the-hollow-canopy",
    "title": "Three days",
    "filename": "three-days.png",
    "relativePath": "assets/images/the-hollow-canopy/timeline/three-days.png",
    "publicPath": "/assets/images/the-hollow-canopy/timeline/three-days.png",
    "status": "missing"
  },
  {
    "id": "the-seal",
    "category": "timeline",
    "bookSlug": "the-hollow-canopy",
    "title": "The Bell is sealed",
    "filename": "the-seal.png",
    "relativePath": "assets/images/the-hollow-canopy/timeline/the-seal.png",
    "publicPath": "/assets/images/the-hollow-canopy/timeline/the-seal.png",
    "status": "missing"
  },
  {
    "id": "the-hum",
    "category": "timeline",
    "bookSlug": "the-hollow-canopy",
    "title": "One note higher",
    "filename": "the-hum.png",
    "relativePath": "assets/images/the-hollow-canopy/timeline/the-hum.png",
    "publicPath": "/assets/images/the-hollow-canopy/timeline/the-hum.png",
    "status": "missing"
  },
  {
    "id": "the-vein",
    "category": "magic",
    "bookSlug": "the-hollow-canopy",
    "title": "The Vein",
    "filename": "the-vein.png",
    "relativePath": "assets/images/the-hollow-canopy/magic/the-vein.png",
    "publicPath": "/assets/images/the-hollow-canopy/magic/the-vein.png",
    "status": "missing"
  },
  {
    "id": "knot-glyph",
    "category": "magic",
    "bookSlug": "the-hollow-canopy",
    "title": "Selenqari knot-glyphs",
    "filename": "knot-glyph.png",
    "relativePath": "assets/images/the-hollow-canopy/magic/knot-glyph.png",
    "publicPath": "/assets/images/the-hollow-canopy/magic/knot-glyph.png",
    "status": "missing"
  },
  {
    "id": "marrow-bell-skill",
    "category": "magic",
    "bookSlug": "the-hollow-canopy",
    "title": "The Marrow Bell",
    "filename": "marrow-bell-skill.png",
    "relativePath": "assets/images/the-hollow-canopy/magic/marrow-bell-skill.png",
    "publicPath": "/assets/images/the-hollow-canopy/magic/marrow-bell-skill.png",
    "status": "missing"
  },
  {
    "id": "scent-protocol",
    "category": "magic",
    "bookSlug": "the-hollow-canopy",
    "title": "Blocker protocol",
    "filename": "scent-protocol.png",
    "relativePath": "assets/images/the-hollow-canopy/magic/scent-protocol.png",
    "publicPath": "/assets/images/the-hollow-canopy/magic/scent-protocol.png",
    "status": "missing"
  },
  {
    "id": "hc-ch-0001-opening",
    "category": "scenes",
    "bookSlug": "the-hollow-canopy",
    "title": "The Man They Sent — Chapter Opening",
    "filename": "hc-ch-0001-opening.png",
    "relativePath": "assets/images/the-hollow-canopy/scenes/hc-ch-0001-opening.png",
    "publicPath": "/assets/images/the-hollow-canopy/scenes/hc-ch-0001-opening.png",
    "status": "missing"
  },
  {
    "id": "hc-ch-0002-opening",
    "category": "scenes",
    "bookSlug": "the-hollow-canopy",
    "title": "The Initial — Chapter Opening",
    "filename": "hc-ch-0002-opening.png",
    "relativePath": "assets/images/the-hollow-canopy/scenes/hc-ch-0002-opening.png",
    "publicPath": "/assets/images/the-hollow-canopy/scenes/hc-ch-0002-opening.png",
    "status": "missing"
  },
  {
    "id": "hc-ch-0003-opening",
    "category": "scenes",
    "bookSlug": "the-hollow-canopy",
    "title": "Asset Orchid — Chapter Opening",
    "filename": "hc-ch-0003-opening.png",
    "relativePath": "assets/images/the-hollow-canopy/scenes/hc-ch-0003-opening.png",
    "publicPath": "/assets/images/the-hollow-canopy/scenes/hc-ch-0003-opening.png",
    "status": "missing"
  }
] as ImageManifestEntry[],
};

export function getManifestByCategory(category: ImageCategory) {
  return imageManifest.entries.filter((e) => e.category === category);
}
