/** AUTO-GENERATED by seed/scripts/sync-book-codex.mjs */
export const magicSkills = [
  {
    "id": "the-vein",
    "name": "The Vein",
    "type": "phenomenon",
    "description": "The low hum in water, bone, and radio through the Orrocanopy. It is the Marrow listening for a pattern to finish.",
    "rank": "S",
    "color": "#553c9a",
    "promptId": "the-vein",
    "firstAppearance": "ch-0009"
  },
  {
    "id": "knot-glyph",
    "name": "Selenqari knot-glyphs",
    "type": "language",
    "description": "A script of stone cords read by touch and shadow-angle. In the city's grammar, ask and finish are the same word.",
    "rank": "A",
    "color": "#553c9a",
    "promptId": "knot-glyph",
    "firstAppearance": "ch-0010"
  },
  {
    "id": "marrow-bell-skill",
    "name": "The Marrow Bell",
    "type": "artifact",
    "description": "A cistern-heart that submits a living question to the Marrow. The answer arrives as completion of flesh and system, not as words.",
    "rank": "S",
    "color": "#553c9a",
    "promptId": "marrow-bell-skill",
    "firstAppearance": "ch-0041"
  },
  {
    "id": "scent-protocol",
    "name": "Blocker protocol",
    "type": "military",
    "description": "Twelve-hour scent blockers and logged suppressants. An alpha protection officer leaves the tent if an omega's suppressants fail.",
    "rank": "C",
    "color": "#553c9a",
    "promptId": "scent-protocol",
    "firstAppearance": "ch-0001"
  }
];
export const manaLaws: string[] = [];
export const magicMaterials: { id: string; name: string; description: string }[] = [];
export const magicRecipes: { id: string; name: string; description: string }[] = [];
