/** AUTO-GENERATED by seed/scripts/sync-books-registry.mjs — edit seed/books.json and per-book book.json */
import type { Book } from "@/types/book";

export const libraryName = `Aether Vale Digital Library`;

export const books: Book[] = [
  {
    "id": "rapture-cycle",
    "slug": "rapture",
    "title": "Rapture",
    "subtitle": "The Fractured Sky",
    "author": "Aether Vale",
    "description": "When the sky fractures and dragons fall, an ordinary omega named Cassian Reed survives among strangers who will become family, founders, and rivals—while the slow bond between him and alpha Adrian Hale grows across catastrophe, rebuilding, and choice.",
    "genre": [
      "Post-Apocalyptic Fantasy",
      "Survival",
      "Romance",
      "Epic Fantasy"
    ],
    "accentColor": "#8b6b2e",
    "coverImage": "/assets/covers/rapture.svg",
    "features": {
      "codex": true,
      "bestiary": true,
      "map": true,
      "timeline": true,
      "relationships": true
    },
    "totalChapters": 1200,
    "totalVolumes": 21
  },
  {
    "id": "echoes-of-the-void",
    "slug": "echoes-of-the-void",
    "title": "Echoes of the Void",
    "subtitle": "The Omega Who Became the End",
    "author": "Aether Vale",
    "description": "An average, unloved transmigrator reborn as an unwanted spare omega tries again and again across secret time loops to find peace and love—until exhaustion and betrayal transform him into the absolute End of everything.",
    "genre": [
      "Dark Fantasy",
      "Omegaverse",
      "Time Loop",
      "Political Intrigue",
      "MM Romance"
    ],
    "accentColor": "#4a3f6b",
    "coverImage": "/assets/covers/echoes-of-the-void.svg",
    "features": {
      "codex": true,
      "bestiary": false,
      "map": false,
      "timeline": true,
      "relationships": true
    },
    "totalChapters": 360,
    "totalVolumes": 8
  }
] as Book[];

export function getBookBySlug(slug: string): Book | undefined {
  return books.find((b) => b.slug === slug);
}

export function getDefaultBook(): Book {
  return books[0];
}
