/** AUTO-GENERATED by seed/scripts/sync-app-data.mjs */
export interface Companion {
  id: string;
  name: string;
  species: string;
  bondedTo: string | null;
  role: string;
  description: string;
  traits: string[];
  firstAppearance: string;
  imageColor: string;
}

export const companions: Companion[] = [
  {
    id: "ash",
    name: "Ash",
    species: "Dire Ashwolf",
    bondedTo: "atlas-hale",
    role: "Combat companion",
    description: "Black wolf with ember markings and amber eyes. Brave, stubborn, protective. Evolution: Ash Cub → Ashwolf → Dire Ashwolf → Ember Fang → Ash King.",
    traits: ["Brave","Stubborn","Protective"],
    firstAppearance: "ch-0845",
    imageColor: "#1a202c",
  },
  {
    id: "whisper",
    name: "Whisper",
    species: "Sky Razor Hawk",
    bondedTo: "nora-winters",
    role: "Scout companion",
    description: "Silver hawk with moon feathers and golden eyes. Intelligent, mischievous, curious — Nora's scout and messenger.",
    traits: ["Intelligent","Mischievous","Curious"],
    firstAppearance: "ch-0006",
    imageColor: "#a0aec0",
  },
  {
    id: "bramble",
    name: "Bramble",
    species: "World Tree Guardian Cub",
    bondedTo: "lily-vale",
    role: "Healing companion",
    description: "Fox-like creature with leaf fur and green eyes. Playful, gentle — future symbol of Sanctuary.",
    traits: ["Playful","Gentle","Loyal"],
    firstAppearance: "ch-0500",
    imageColor: "#276749",
  },
  {
    id: "tempest",
    name: "Tempest",
    species: "Storm Drake",
    bondedTo: "adrian-hale",
    role: "Guardian drake",
    description: "Blue scales, lightning-edged wings. Proud, fearless, competitive — argues with Adrian. Not a true dragon.",
    traits: ["Proud","Fearless","Competitive"],
    firstAppearance: "ch-0600",
    imageColor: "#2b6cb0",
  },
  {
    id: "lumen",
    name: "Lumen",
    species: "Aether Spirit",
    bondedTo: "cassian-reed",
    role: "Aether companion",
    description: "Crystal spirit form, silver-blue light. Wise, sarcastic, ancient — perspective without easy answers. Late saga only.",
    traits: ["Wise","Sarcastic","Ancient"],
    firstAppearance: "ch-0900",
    imageColor: "#5a6bcf",
  },
  {
    id: "astralis",
    name: "Astralis",
    species: "Star Dragon",
    bondedTo: null,
    role: "Mythic ally",
    description: "Celestial dragon of constellations. Mythic endgame ally — alliance never ownership.",
    traits: ["Celestial","Ancient","Mythic"],
    firstAppearance: "ch-1150",
    imageColor: "#d4af37",
  }
];

export function getCompanionById(id: string) {
  return companions.find((c) => c.id === id);
}
