/** AUTO-GENERATED by seed/scripts/sync-app-data.mjs */
export interface DungeonFloor {
  floors: string;
  rank: string;
  monsters?: string[];
  loot: string[];
  boss?: boolean | string;
}

export interface Dungeon {
  id: string;
  name: string;
  classification: string;
  theme: string;
  floors: string | number;
  entrance: string;
  appearance: string;
  rule?: string;
  sovereign?: string | null;
  dominantMonsters: string[];
  floorTable: DungeonFloor[];
  rewards: string[];
  storySignificance?: string;
  clearedChapter?: string;
  imageColor: string;
  firstAppearance?: string;
}

export const dungeons: Dungeon[] = [
  {
    id: "first-dungeon",
    name: "The First Dungeon (Ashford Undercity)",
    classification: "major",
    theme: "discovery",
    floors: 12,
    entrance: "Subterranean street door east of Ashford",
    appearance: "Preserved underground city; electric amber lights; no bodies",
    rule: "Lights activate for visitors; doors seal behind party",
    sovereign: null,
    dominantMonsters: ["forgotten-knight","echo-servant","whisper-shade"],
    floorTable: [{"floors":"1-3","rank":"E-D","monsters":["grave-walker","glimmer-rat"],"loot":["salvaged-rations","rusted-scrap"]},{"floors":"4-6","rank":"D-C","monsters":["forgotten-knight","rift-hound"],"loot":["rune-fragment-d","ancient-coin"]},{"floors":"7-9","rank":"C-B","monsters":["echo-servant","memory-wraith"],"loot":["memory-glass-shard","archive-tablet"]},{"floors":"10-12","rank":"B-A","monsters":["dungeon-guardian-construct"],"loot":["connected-worlds-map","rune-archive-core"],"boss":true}],
    rewards: ["Ancient records","Rune system knowledge","Connected worlds map"],
    storySignificance: "critical",
    clearedChapter: "ch-0180",
    imageColor: "#3d4f5f",
    firstAppearance: "ch-0030",
  },
  {
    id: "forgotten-palace",
    name: "The Forgotten Palace",
    classification: "legacy",
    theme: "memory",
    floors: 33,
    entrance: "",
    appearance: "",
    rule: "Deeper travel = more memories lost (personal, not plot-critical without consent)",
    sovereign: "pale-king",
    dominantMonsters: ["memory-wraith","forgotten-knight","echo-servant"],
    floorTable: [{"floors":"1-8","rank":"C","loot":["pale-steel-fragment","memory-glass-shard"]},{"floors":"9-20","rank":"B","loot":["echo-crystal","forbidden-scroll"]},{"floors":"21-32","rank":"A","loot":["memory-shard","pale-crown-fragment"]},{"floors":"33","rank":"S","boss":"pale-king","loot":["memory-shard-legendary","truth-of-empire-fragment"]}],
    rewards: ["Lost knowledge","Forbidden memories","Identity truths"],
    storySignificance: "",
    clearedChapter: "",
    imageColor: "#3d4f5f",
    firstAppearance: "",
  },
  {
    id: "eternal-machine",
    name: "The Eternal Machine",
    classification: "legacy",
    theme: "control",
    floors: 51,
    entrance: "",
    appearance: "",
    rule: "All actions follow precise laws; violations trigger Clockwork Soldiers",
    sovereign: "clockwork-empress",
    dominantMonsters: ["clockwork-soldier","gear-beast","bronze-sentinel"],
    floorTable: [{"floors":"1-15","rank":"C-B","loot":["bronze-gear","law-tablet"]},{"floors":"16-35","rank":"B-A","loot":["master-gear","mana-engine-schematic"]},{"floors":"36-50","rank":"A-S","loot":["bronze-heart-fragment"]},{"floors":"51","rank":"S","boss":"clockwork-empress","loot":["bronze-heart-engine"]}],
    rewards: [],
    storySignificance: "",
    clearedChapter: "",
    imageColor: "#3d4f5f",
    firstAppearance: "",
  },
  {
    id: "crimson-hive",
    name: "The Crimson Hive",
    classification: "major",
    theme: "evolution",
    floors: 27,
    entrance: "",
    appearance: "",
    rule: "Dungeon adapts; repeated strategies stop working after 3 uses",
    sovereign: "brood-mother",
    dominantMonsters: ["hive-soldier","brood-hunter","crimson-swarmer"],
    floorTable: [{"floors":"1-10","rank":"D-C","loot":["hive-chitin","evolution-ichor"]},{"floors":"11-22","rank":"B-A","loot":["royal-gel","hunter-chitin"]},{"floors":"23-27","rank":"A-S","boss":"brood-mother","loot":["evolution-core","hive-crown"]}],
    rewards: [],
    storySignificance: "",
    clearedChapter: "",
    imageColor: "#3d4f5f",
    firstAppearance: "",
  },
  {
    id: "abyssal-ocean",
    name: "The Abyssal Ocean",
    classification: "catastrophe",
    theme: "fear-of-unknown",
    floors: "unknown",
    entrance: "",
    appearance: "",
    rule: "Maps inaccurate; distances change; navigation fails",
    sovereign: null,
    dominantMonsters: ["abyssal-maw","deep-one","leviathan-serpent"],
    floorTable: [],
    rewards: [],
    storySignificance: "",
    clearedChapter: "",
    imageColor: "#3d4f5f",
    firstAppearance: "",
  },
  {
    id: "city-of-shadows",
    name: "The City of Shadows",
    classification: "legacy",
    theme: "regret",
    floors: "city-scale",
    entrance: "",
    appearance: "",
    rule: "Every visitor encounters manifestations of personal regret",
    sovereign: null,
    dominantMonsters: ["shadow-citizen","twilight-stalker","regret-spirit"],
    floorTable: [],
    rewards: [],
    storySignificance: "",
    clearedChapter: "",
    imageColor: "#3d4f5f",
    firstAppearance: "",
  },
  {
    id: "world-tree",
    name: "The World Tree",
    classification: "civilization",
    theme: "life",
    floors: "hundreds-vertical",
    entrance: "",
    appearance: "",
    rule: "Each level contains different biome",
    sovereign: null,
    dominantMonsters: ["forest-guardian","sky-serpent","ancient-spirit"],
    floorTable: [],
    rewards: [],
    storySignificance: "",
    clearedChapter: "",
    imageColor: "#3d4f5f",
    firstAppearance: "",
  },
  {
    id: "limbo",
    name: "Limbo",
    classification: "unique",
    theme: "loneliness",
    floors: "infinite-fragmented",
    entrance: "",
    appearance: "",
    rule: "Time 100:3 inside:outside; identity instability",
    sovereign: null,
    dominantMonsters: [],
    floorTable: [],
    rewards: [],
    storySignificance: "",
    clearedChapter: "",
    imageColor: "#3d4f5f",
    firstAppearance: "",
  }
];

export function getDungeonById(id: string) {
  return dungeons.find((d) => d.id === id);
}
