/** AUTO-GENERATED by seed/scripts/sync-app-data.mjs */
export interface Faction {
  id: string;
  name: string;
  type: string;
  alignment: string;
  philosophy: string;
  description: string;
  leaderIds: string[];
  imageColor: string;
  firstAppearance?: string;
}

export const factions: Faction[] = [
  {
    id: "sanctuary",
    name: "Sanctuary",
    type: "civilization",
    alignment: "ally",
    philosophy: "Humanity survives together",
    description: "Humanity survives together — Can compassion survive?",
    leaderIds: ["cassian-reed","adrian-hale"],
    imageColor: "#5a6bcf",
    firstAppearance: "ch-0266",
  },
  {
    id: "iron-dominion",
    name: "Iron Dominion",
    type: "nation",
    alignment: "rival",
    philosophy: "Order above freedom",
    description: "Order above freedom — Is freedom worth instability?",
    leaderIds: ["viktor-drake"],
    imageColor: "#5a6bcf",
    firstAppearance: "ch-0380",
  },
  {
    id: "free-cities",
    name: "Free Cities",
    type: "trade-alliance",
    alignment: "ally",
    philosophy: "Prosperity through cooperation",
    description: "Prosperity through cooperation",
    leaderIds: [],
    imageColor: "#5a6bcf",
    firstAppearance: "ch-0387",
  },
  {
    id: "skyborne-league",
    name: "Skyborne League",
    type: "confederation",
    alignment: "ally",
    philosophy: "Knowledge belongs to everyone",
    description: "Knowledge belongs to everyone",
    leaderIds: [],
    imageColor: "#5a6bcf",
    firstAppearance: "ch-0393",
  },
  {
    id: "crimson-faith",
    name: "Crimson Ascension",
    type: "religion",
    alignment: "complicated",
    philosophy: "Humanity must evolve",
    description: "Humanity must evolve — Do people need belief?",
    leaderIds: ["mother-seraphine"],
    imageColor: "#5a6bcf",
    firstAppearance: "ch-0500",
  },
  {
    id: "deep-delvers-guild",
    name: "Deep Delvers Guild",
    type: "guild",
    alignment: "ally",
    philosophy: "Dungeon exploration and knowledge",
    description: "Dungeon exploration and knowledge",
    leaderIds: [],
    imageColor: "#5a6bcf",
    firstAppearance: "ch-0400",
  },
  {
    id: "golden-exchange",
    name: "Golden Exchange",
    type: "merchant-consortium",
    alignment: "neutral",
    philosophy: "Control trade and resources",
    description: "Control trade and resources",
    leaderIds: [],
    imageColor: "#5a6bcf",
    firstAppearance: "ch-0390",
  },
  {
    id: "dragon-conclave",
    name: "Dragon Conclave",
    type: "monster-civilization",
    alignment: "ally",
    philosophy: "Dragons steward the world",
    description: "Dragons steward the world — Who truly owns Earth?",
    leaderIds: ["velkarion"],
    imageColor: "#5a6bcf",
    firstAppearance: "ch-0691",
  },
  {
    id: "brood-empire",
    name: "Brood Empire",
    type: "monster-civilization",
    alignment: "hostile",
    philosophy: "Expand, adapt, consume",
    description: "Expand, adapt, consume",
    leaderIds: [],
    imageColor: "#5a6bcf",
    firstAppearance: "ch-0500",
  },
  {
    id: "voss-kingdom",
    name: "Voss Kingdom",
    type: "warlord-state",
    alignment: "enemy",
    philosophy: "",
    description: "",
    leaderIds: ["adrian-voss"],
    imageColor: "#5a6bcf",
    firstAppearance: "ch-0650",
  }
];
