/** AUTO-GENERATED by seed/scripts/sync-app-data.mjs — edit seed/world-map.json */
export type MapNodeType =
  | "city"
  | "fortress"
  | "ruins"
  | "community"
  | "safe-zone"
  | "danger-zone"
  | "wilderness"
  | "dungeon"
  | "realm"
  | "network";

export type MapNodeTier = "major" | "minor";

export interface MapNode {
  id: string;
  name: string;
  type: MapNodeType;
  tier: MapNodeTier;
  x: number;
  y: number;
  description: string;
  significance: string;
  color: string;
  locationId?: string;
  mapLabel?: string;
}

export const mapContinent = {
  name: "Valdris",
  subtitle: "The Shattered Continent — sole survivable landmass after the Rapture",
  ocean: "Fracture Ocean (impassable mana storms; no intercontinental travel)",
};

/** Cartography rectangle inside world-map.png (percent of full image). */
export const mapInset = {
  left: 11,
  top: 16,
  right: 89,
  bottom: 79,
};

/** Convert node coords (0–100 within cartography) to full-image SVG coords. */
export function mapCoordToImage(x: number, y: number) {
  const w = mapInset.right - mapInset.left;
  const h = mapInset.bottom - mapInset.top;
  return {
    x: mapInset.left + (x / 100) * w,
    y: mapInset.top + (y / 100) * h,
  };
}

export const mapNodes: MapNode[] = [
  {
    id: "forgotten-palace",
    name: "Forgotten Palace",
    type: "dungeon",
    tier: "major",
    x: 14,
    y: 11,
    description: "White palace in mist — memories traded for depth.",
    significance: "Pale King sovereign dungeon.",
    color: "#d4af37",
    locationId: "forgotten-palace",
    mapLabel: "FORGOTTEN PALACE"
  },
  {
    id: "archive-spires",
    name: "Archive Spires",
    type: "ruins",
    tier: "major",
    x: 24,
    y: 30,
    description: "Aetherian capital spires — largest pre-Rapture library still standing.",
    significance: "Cycle lore and mana-tech records.",
    color: "#4a6fa5",
    locationId: "archive-spires",
    mapLabel: "ARCHIVE SPIRES"
  },
  {
    id: "limbo",
    name: "Limbo",
    type: "realm",
    tier: "major",
    x: 6,
    y: 46,
    description: "Dimensional pocket between cycles — islands, broken stars, distorted time.",
    significance: "Cassian's hundred-year arc; 100:3 time ratio.",
    color: "#8b2e8b",
    locationId: "limbo",
    mapLabel: "LIMBO"
  },
  {
    id: "eternal-machine",
    name: "Eternal Machine",
    type: "dungeon",
    tier: "major",
    x: 36,
    y: 13,
    description: "Bronze towers and clockwork law — the Clockwork Empress's domain.",
    significance: "Legacy dungeon of absolute order.",
    color: "#8b7355",
    locationId: "eternal-machine",
    mapLabel: "ETERNAL MACHINE"
  },
  {
    id: "celestial-peaks",
    name: "Celestial Peaks",
    type: "wilderness",
    tier: "major",
    x: 52,
    y: 9,
    description: "Obsidian summits where the Dragon Conclave watches the age turn.",
    significance: "Extreme danger; dragon sovereign domain.",
    color: "#5a6bcf",
    locationId: "celestial-peaks",
    mapLabel: "DRAGON PEAKS"
  },
  {
    id: "fracture-scar",
    name: "Fracture Scar",
    type: "danger-zone",
    tier: "major",
    x: 48,
    y: 21,
    description: "A belt of silver lightning and unstable mana where reality thins.",
    significance: "Rift storm danger zone crossing the northern interior.",
    color: "#6b3fa0",
    mapLabel: "FRACTURE SCAR"
  },
  {
    id: "world-tree",
    name: "World Tree",
    type: "dungeon",
    tier: "major",
    x: 76,
    y: 14,
    description: "Colossal tree through the clouds — biomes stacked on every branch.",
    significance: "Civilization dungeon; Bramble's origin.",
    color: "#2d6b3d",
    locationId: "world-tree",
    mapLabel: "WORLD TREE"
  },
  {
    id: "black-stone",
    name: "Black Stone",
    type: "fortress",
    tier: "major",
    x: 70,
    y: 24,
    description: "Viktor Drake's iron capital — order, conscription, industrial salvation.",
    significance: "Iron Dominion seat of power.",
    color: "#8b2e2e",
    locationId: "dominion-capital",
    mapLabel: "BLACK STONE"
  },
  {
    id: "city-of-shadows",
    name: "City of Shadows",
    type: "dungeon",
    tier: "major",
    x: 46,
    y: 36,
    description: "Twilight ruins where regret takes shape — a sovereign-less dungeon city.",
    significance: "Legacy dungeon; personal horror theme.",
    color: "#3d3550",
    locationId: "city-of-shadows",
    mapLabel: "CITY OF SHADOWS"
  },
  {
    id: "stonebridge-outpost",
    name: "Stonebridge",
    type: "community",
    tier: "minor",
    x: 40,
    y: 46,
    description: "A fortified bridge-town taxing trade along the central river.",
    significance: "Minor trade hub between west ruins and eastern valleys.",
    color: "#6b5b4f",
    mapLabel: "Stonebridge"
  },
  {
    id: "riverbend-hold",
    name: "Riverbend Hold",
    type: "safe-zone",
    tier: "minor",
    x: 54,
    y: 44,
    description: "Walled farming commune on a bend of the Valdris River — militia, granaries, bells.",
    significance: "Minor safe settlement; Sanctuary trade partner.",
    color: "#4a7c59",
    mapLabel: "Riverbend"
  },
  {
    id: "ashwolf-forest",
    name: "Ashwolf Forest",
    type: "danger-zone",
    tier: "major",
    x: 30,
    y: 50,
    description: "First named monster territory — ash-grey wolves and grave-walkers between the trees.",
    significance: "High danger wilds; early delver proving ground.",
    color: "#5c1a1a",
    locationId: "ashwolf-forest",
    mapLabel: "ASHWOLF FOREST"
  },
  {
    id: "mana-convergence",
    name: "Mana Convergence",
    type: "network",
    tier: "minor",
    x: 50,
    y: 51,
    description: "Where ley-lines cross beneath Valdris — dungeons and awakenings spike nearby.",
    significance: "World network node; sovereign territories anchor here.",
    color: "#5a6bcf",
    mapLabel: "Convergence"
  },
  {
    id: "sanctuary",
    name: "Sanctuary",
    type: "city",
    tier: "major",
    x: 62,
    y: 50,
    description: "White stone walls, Founder's Tree, healers — humanity's enduring hope.",
    significance: "Founded by Cassian Reed and Adrian Hale.",
    color: "#4f8b5a",
    locationId: "sanctuary",
    mapLabel: "SANCTUARY"
  },
  {
    id: "sanctuary-valley",
    name: "Sanctuary Valley",
    type: "safe-zone",
    tier: "major",
    x: 58,
    y: 56,
    description: "Fertile defensible valley chosen for humanity's beacon.",
    significance: "Pre-city sanctuary site; low-moderate danger.",
    color: "#3d6b4f",
    locationId: "sanctuary-valley",
    mapLabel: "SANCTUARY VALLEY"
  },
  {
    id: "crimson-wastes",
    name: "Crimson Wastes",
    type: "danger-zone",
    tier: "major",
    x: 84,
    y: 42,
    description: "Organic hive tunnels breach the surface — evolution never sleeps.",
    significance: "Brood Mother territory; extreme danger.",
    color: "#8b1a1a",
    mapLabel: "CRIMSON WASTES"
  },
  {
    id: "crimson-hive",
    name: "Crimson Hive",
    type: "dungeon",
    tier: "major",
    x: 80,
    y: 56,
    description: "Living dungeon of chitin corridors and royal gel.",
    significance: "Major sovereign dungeon — Brood Mother.",
    color: "#a02020",
    locationId: "crimson-hive",
    mapLabel: "CRIMSON HIVE"
  },
  {
    id: "ironhorn-plains",
    name: "Ironhorn Plains",
    type: "danger-zone",
    tier: "major",
    x: 74,
    y: 60,
    description: "Stampeding territorial beasts across open grassland.",
    significance: "Moderate–high danger hunting grounds.",
    color: "#8b5a2e",
    locationId: "ironhorn-plains",
    mapLabel: "IRONHORN PLAINS"
  },
  {
    id: "millhaven",
    name: "Millhaven",
    type: "community",
    tier: "minor",
    x: 66,
    y: 70,
    description: "Windmills and terraced fields under Sanctuary's protection charter.",
    significance: "Eastern agricultural minor community.",
    color: "#7a8b5a",
    mapLabel: "Millhaven"
  },
  {
    id: "old-crossing",
    name: "Old Crossing",
    type: "community",
    tier: "minor",
    x: 26,
    y: 60,
    description: "Refugee tents where Ashford evacuees first regrouped along the coastal road.",
    significance: "Minor survivor community; pre-Highway Camp.",
    color: "#a08050",
    mapLabel: "Old Crossing"
  },
  {
    id: "highway-camp",
    name: "Highway Camp",
    type: "community",
    tier: "major",
    x: 40,
    y: 64,
    description: "Abandoned interstate turned survivor corridor — cookfires, watchtowers, fragile trust.",
    significance: "Where strangers become family before Sanctuary rises.",
    color: "#744210",
    locationId: "highway-camp",
    mapLabel: "HIGHWAY CAMP"
  },
  {
    id: "new-hope",
    name: "New Hope",
    type: "community",
    tier: "minor",
    x: 46,
    y: 67,
    description: "A failed settlement attempt — walls half-built, gardens reclaimed by mana-touched weeds.",
    significance: "Cautionary minor community on the road east.",
    color: "#8b7355",
    mapLabel: "New Hope"
  },
  {
    id: "ashford",
    name: "Ashford",
    type: "ruins",
    tier: "major",
    x: 20,
    y: 70,
    description: "Cassian's fallen metropolis — ground zero where the sky first tore.",
    significance: "Fractured City; Day Zero broadcast origin.",
    color: "#8b6b2e",
    locationId: "ashford",
    mapLabel: "ASHFORD"
  },
  {
    id: "first-dungeon",
    name: "Ashford Undercity",
    type: "dungeon",
    tier: "major",
    x: 26,
    y: 73,
    description: "Preserved subterranean streets — amber lights, sealed doors, the First Dungeon.",
    significance: "Discovery of dungeon law and rune archives.",
    color: "#c9a227",
    locationId: "first-dungeon",
    mapLabel: "UNDERCITY"
  },
  {
    id: "ashford-harbor",
    name: "Ashford Harbor",
    type: "ruins",
    tier: "major",
    x: 14,
    y: 76,
    description: "Black water under a silver wound — the harbor fracture seen live worldwide.",
    significance: "First visible Rapture breach.",
    color: "#7a5c28",
    locationId: "ashford-harbor",
    mapLabel: "HARBOR RIFT"
  },
  {
    id: "abyssal-ocean",
    name: "Abyssal Gate",
    type: "dungeon",
    tier: "major",
    x: 50,
    y: 80,
    description: "Coastal rift descending into starless depths — maps lie here.",
    significance: "Catastrophe dungeon; leviathan territory.",
    color: "#1a3a5c",
    locationId: "abyssal-ocean",
    mapLabel: "ABYSSAL GATE"
  }
];

export function getMapNodeById(id: string) {
  return mapNodes.find((n) => n.id === id);
}

export function getMapNodesByTier(tier: MapNodeTier) {
  return mapNodes.filter((n) => n.tier === tier);
}
